from typing import List
from . import RegNames

Sector_Numbers: List[str] = ["1","2","3","4","5","6","7","8","9","X","Z","Y"]
Basic_Weapons: List[str] = [
    "Machine Gun",
    "Rocket Launcher",
    "MPFB Devastator",
    "Resonance Detonator",
    "Pulse Cannon",
    "Shocksplinter",
    "Cyclic Fusion Ignition System"
]
Stat_Names: List[str] = [
    "Health",
    "Attack",
    "Assimilate",
    "Strength",
    "Crack",
    "Tasen",
    "Komato"
]

Levels: List[List[str]] = list(list("Sector "+i+" - Level "+str(j) for j in range(1,6)) for i in Sector_Numbers[:10])
Sector_Complete: List[str] = list("Sector "+i+" - Sector Complete" for i in Sector_Numbers)
Stat_Levels: List[List[str]] = list(list("Reach "+i+" Level "+str(j) for j in range(1,11))+["Reach Max "+i+"Level"] for i in Stat_Names)

Stat_Health: List[str] = [
    "Reach Health Level 1",
    "Reach Health Level 2",
    "Reach Health Level 3",
    "Reach Health Level 4",
    "Reach Health Level 5",
    "Reach Health Level 6",
    "Reach Health Level 7",
    "Reach Health Level 8",
    "Reach Health Level 9",
    "Reach Health Level 10",
    "Reach Max Health Level"
]
Stat_Attack: List[str] = [
    "Reach Attack Level 1",
    "Reach Attack Level 2",
    "Reach Attack Level 3",
    "Reach Attack Level 4",
    "Reach Attack Level 5",
    "Reach Attack Level 6",
    "Reach Attack Level 7",
    "Reach Attack Level 8",
    "Reach Attack Level 9",
    "Reach Attack Level 10",
    "Reach Max Attack Level"
]
Stat_Assimilate: List[str] = [
    "Reach Assimilate Level 1",
    "Reach Assimilate Level 2",
    "Reach Assimilate Level 3",
    "Reach Assimilate Level 4",
    "Reach Assimilate Level 5",
    "Reach Assimilate Level 6",
    "Reach Assimilate Level 7",
    "Reach Assimilate Level 8",
    "Reach Assimilate Level 9",
    "Reach Assimilate Level 10",
    "Reach Max Assimilate Level"
]
Stat_Strength: List[str] = [
    "Reach Strength Level 1",
    "Reach Strength Level 2",
    "Reach Strength Level 3",
    "Reach Strength Level 4",
    "Reach Strength Level 5",
    "Reach Strength Level 6",
    "Reach Strength Level 7",
    "Reach Strength Level 8",
    "Reach Strength Level 9",
    "Reach Strength Level 10",
    "Reach Max Strength Level"
]
Stat_Crack: List[str] = [
    "Reach Crack Level 1",
    "Reach Crack Level 2",
    "Reach Crack Level 3",
    "Reach Crack Level 4",
    "Reach Crack Level 5",
    "Reach Crack Level 6",
    "Reach Crack Level 7",
    "Reach Crack Level 8",
    "Reach Crack Level 9",
    "Reach Crack Level 10",
    "Reach Max Crack Level"
]
Stat_Tasen: List[str] = [
    "Reach Tasen Level 1",
    "Reach Tasen Level 2",
    "Reach Tasen Level 3",
    "Reach Tasen Level 4",
    "Reach Tasen Level 5",
    "Reach Tasen Level 6",
    "Reach Tasen Level 7",
    "Reach Tasen Level 8",
    "Reach Tasen Level 9",
    "Reach Tasen Level 10",
    "Reach Max Tasen Level"
]
Stat_Komato: List[str] = [
    "Reach Komato Level 1",
    "Reach Komato Level 2",
    "Reach Komato Level 3",
    "Reach Komato Level 4",
    "Reach Komato Level 5",
    "Reach Komato Level 6",
    "Reach Komato Level 7",
    "Reach Komato Level 8",
    "Reach Komato Level 9",
    "Reach Komato Level 10",
    "Reach Max Komato Level"
]

Posters: List[str] = [
    "Sector 1 - Poster",
    "Sector 2 - Poster",
    "Sector 3 - Poster",
    "Sector 4 - Poster",
    "Sector 5 - Poster",
    "Sector 6 - Poster",
    "Sector 7 - Poster",
    "Sector 8 - Poster",
    "Sector 9 - Poster",
    "Sector X - Poster",
    "Sector Z - Epic Poster",
    "Sector Y - Poster of Doom"
]

Ribbons: List[str] = [
    "Sector 1 - Ribbon",
    "Sector 2 - Ribbon",
    "Sector 3 - Ribbon",
    "Sector 4 - Ribbon",
    "Sector 5 - Ribbon",
    "Sector 6 - Ribbon",
    "Sector 7 - Ribbon",
    "Sector 8 - Ribbon",
    "Sector 9 - Ribbon",
    "Sector X - Ribbon"
]

Supercharges: List[str] = [
    "Sector 1 - Supercharge",
    "Sector 2 - Supercharge",
    "Sector 3 - Supercharge",
    "Sector 4 - Supercharge",
    "Sector 5 - Supercharge",
    "Sector 6 - Supercharge",
    "Sector 7 - Supercharge",
    "Sector 8 - Supercharge",
    "Sector 9 - Supercharge",
    "Sector X - Supercharge"
]

Tutorial_Pages: List[str] = [
    "Sector 1 - Tutorial Page 1",
    "Sector 1 - Tutorial Page 2",
    "Sector 1 - Tutorial Page 3",
    "Sector 1 - Tutorial Page 4",
    "Sector 1 - Tutorial Page 5",
    "Sector 1 - Tutorial Page 6"
]

Upgrades_Jump: List[str] = [
    "Sector 2 - Jump Upgrade",
    "Sector 5 - Jump Upgrade"
]

Upgrades_Armor: List[str] = [
    "Sector 3 - Armor Upgrade",
    "Sector 7 - Armor Upgrade",
    "Sector 8 - Armor Upgrade",
    "Sector 9 - Armor Upgrade",
    "Sector X - Armor Upgrade"
]

Weapons_First: List[str] = [
    "Obtain Machine Gun",
    "Obtain Rocket Launcher",
    "Obtain MPFB Devastator",
    "Obtain Resonance Detonator",
    "Obtain Pulse Cannon",
    "Obtain Shocksplinter",
    "Obtain Cyclic Fusion Ignition System"
]
Weapons_Combined: List[str] = [
"Obtain Buster Gun",
"Obtain Splintergun",
"Obtain Spread Rockets",
"Obtain Nuke",
"Obtain Resonance Reflector",
"Obtain Hyper Pulse",
"Obtain Plasma Cannon",
"Obtain Velocithor V2-10"
]

Weapon_Banana = "Obtain Banana Gun"
Weapon_Massacre = "Obtain Massacre"
Weapon_Null = "Obtain Null Driver"

Weapons_Per_Sector: List[List[str]] = [
["Sector 1 - Machine Gun"],
["Sector 2 - Machine Gun",
 "Sector 2 - Rocket Launcher",
 "Sector 2 - Resonance Detonator"],
["Sector 3 - Machine Gun",
 "Sector 3 - Rocket Launcher",
 "Sector 3 - Resonance Detonator",
 "Sector 3 - Pulse Cannon"],
["Sector 4 - Machine Gun",
 "Sector 4 - Rocket Launcher",
 "Sector 4 - MPFB Devastator",
 "Sector 4 - Resonance Detonator",
 "Sector 4 - Pulse Cannon"],
["Sector 5 - Machine Gun",
 "Sector 5 - Rocket Launcher",
 "Sector 5 - MPFB Devastator",
 "Sector 5 - Resonance Detonator",
 "Sector 5 - Pulse Cannon",
 "Sector 5 - Shocksplinter"],
["Sector 6 - Machine Gun",
 "Sector 6 - Rocket Launcher",
 "Sector 6 - MPFB Devastator",
 "Sector 6 - Resonance Detonator",
 "Sector 6 - Pulse Cannon",
 "Sector 6 - Shocksplinter",
 "Sector 6 - Cyclic Fusion Ignition System"],
["Sector 7 - Machine Gun",
 "Sector 7 - Rocket Launcher",
 "Sector 7 - MPFB Devastator",
 "Sector 7 - Resonance Detonator",
 "Sector 7 - Pulse Cannon",
 "Sector 7 - Shocksplinter",
 "Sector 7 - Cyclic Fusion Ignition System"],
["Sector 8 - Machine Gun",
 "Sector 8 - Rocket Launcher",
 "Sector 8 - MPFB Devastator",
 "Sector 8 - Resonance Detonator",
 "Sector 8 - Pulse Cannon",
 "Sector 8 - Shocksplinter",
 "Sector 8 - Cyclic Fusion Ignition System"],
["Sector 9 - Machine Gun",
 "Sector 9 - Rocket Launcher",
 "Sector 9 - MPFB Devastator",
 "Sector 9 - Resonance Detonator",
 "Sector 9 - Pulse Cannon",
 "Sector 9 - Shocksplinter",
 "Sector 9 - Cyclic Fusion Ignition System"],
["Sector X - Machine Gun",
 "Sector X - Rocket Launcher",
 "Sector X - MPFB Devastator",
 "Sector X - Resonance Detonator",
 "Sector X - Pulse Cannon",
 "Sector X - Shocksplinter",
 "Sector X - Cyclic Fusion Ignition System",
 "Sector X - Resonance Reflector"],
]

Weapons_All_Instances: List[List[List[str]]] = [
[["Sector 3 - Machine Gun in Storage A","Sector 3 - Machine Gun in Main Entrance Left","Sector 3 - Machine Gun near End"],
 ["Sector 3 - Rocket Launcher in Main Entrance Right","Sector 3 - Rocket Launcher in Secured Box near End"]],
[["Sector 4 - Rocket Launcher near First Terminal","Sector 4 - Rocket Launcher near Checkpoint"]],
[["Sector 5 - Machine Gun Left of First Elevator","Sector 5 - Machine Gun near Floor 3 Terminal"],
 ["Sector 5 - Rocket Launcher after First Elevator","Sector 5 - Rocket Launcher next to Weapon Station"],
 ["Sector 5 - Pulse Cannon in Incoming Goods","Sector 5 - Pulse Cannon in Komato Assault Carrier","Sector 5 - Pulse Cannon near Ribbon"]],
[["Sector 6 - Machine Gun in Neoweapons Research Top","Sector 6 - Machine Gun below Supercharge"],
 ["Sector 6 - Rocket Launcher in Neoweapons Research Bottom","Sector 6 - Rocket Launcher in Neoweapons Research Top","Sector 6 - Rocket Launcher near Ribbon"],
 ["Sector 6 - MPFB Devastator near Supercharge","Sector 6 - MPFB Devastator near Poster"],
 ["Sector 6 - Pulse Cannon in Neoweapons Research Bottom","Sector 6 - Pulse Cannon near Ribbon"],
 ["Sector 6 - Shocksplinter in Ventilation Shaft","Sector 6 - Shocksplinter Left of Elevator","Sector 6 - Shocksplinter near Ribbon"]],
[["Sector 7 - Rocket Launcher at Bottom of First Area","Sector 7 - Rocket Launcher in Armory","Sector 7 - Rocket Launcher after Rooftops"],
 ["Sector 7 - Resonance Detonator in Armory","Sector 7 - Resonance Detonator Left of Internal Security Terminal"],
 ["Sector 7 - Pulse Cannon in Armory","Sector 7 - Pulse Cannon near Ribbon"],
 ["Sector 7 - Shocksplinter in Armory","Sector 7 - Shocksplinter Left of Internal Security Terminal","Sector 7 - Shocksplinter in Secured Box near Ribbon"]],
[["Sector 8 - Rocket Launcher before Collapsible Floor","Sector 8 - Rocket Launcher Right of Second Annihilator","Sector 8 - Rocket Launcher below Armor Upgrade"],
 ["Sector 8 - Pulse Cannon Right of Second Annihilator","Sector 8 - Pulse Cannon below Armor Upgrade"],
 ["Sector 8 - Shocksplinter near Start","Sector 8 - Shocksplinter next to Ribbon"]],
[["Sector 9 - Machine Gun near Start","Sector 9 - Machine Gun in Head Guards' Offices","Sector 9 - Machine Gun in Bunker","Sector 9 - Machine Gun near Poster"],
 ["Sector 9 - Rocket Launcher near Assassin Ambush","Sector 9 - Rocket Launcher at Top of Bulkhead Area","Sector 9 - Rocket Launcher in Break Room","Sector 9 - Rocket Launcher in Bunker","Sector 9 - Rocket Launcher near Poster"],
 ["Sector 9 - MPFB Devastator near Assassin Ambush","Sector 9 - MPFB Devastator in Break Room","Sector 9 - MPFB Devastator in Bunker","Sector 9 - MPFB Devastator near Poster"],
 ["Sector 9 - Resonance Detonator above First Terminal","Sector 9 - Resonance Detonator near Break Room","Sector 9 - Resonance Detonator in Bunker","Sector 9 - Resonance Detonator near Poster"],
 ["Sector 9 - Pulse Cannon near Assassin Ambush","Sector 9 - Pulse Cannon in Head Guards' Offices","Sector 9 - Pulse Cannon in Bunker","Sector 9 - Pulse Cannon near Poster"],
 ["Sector 9 - Shocksplinter near Assassin Ambush","Sector 9 - Shocksplinter in Head Guards' Offices","Sector 9 - Shocksplinter in Bunker","Sector 9 - Shocksplinter near Poster"],
 ["Sector 9 - Cyclic Fusion Ignition System near Ribbon","Sector 9 - Cyclic Fusion Ignition System in Bunker","Sector 9 - Cyclic Fusion Ignition System near Poster"]],
[["Sector X - Machine Gun at Top of First Area","Sector X - Machine Gun in Megacore Control","Sector X - Machine Gun before General Tor"],
 ["Sector X - Rocket Launcher in Megacore Control","Sector X - Rocket Launcher before Helios Labs","Sector X - Rocket Launcher before General Tor", "Sector X - Rocket Launcher at Bottom of First Area"],
 ["Sector X - MPFB Devastator in Icarus Labs","Sector X - MPFB Devastator before Helios Labs","Sector X - MPFB Devastator before General Tor","Sector X - MPFB Devastator Right of Asha"],
 ["Sector X - Resonance Detonator in Icarus Labs","Sector X - Resonance Detonator Right of Asha"],
 ["Sector X - Pulse Cannon at Bottom of First Area","Sector X - Pulse Cannon in Megacore Control","Sector X - Pulse Cannon before Helios Labs","Sector X - Pulse Cannon before General Tor"],
 ["Sector X - Shocksplinter below Rooftop Elevator","Sector X - Shocksplinter before Helios Labs","Sector X - Shocksplinter before General Tor"],
 ["Sector X - Cyclic Fusion Ignition System in Megacore Control","Sector X - Cyclic Fusion Ignition System Left of Rooftop Elevator","Sector X - Cyclic Fusion Ignition System before Helios Labs","Sector X - Cyclic Fusion Ignition System before General Tor"]]
]

Logbooks: List[List[str]] = [
["Sector Z - Logbook in Hero Area", "Sector Z - Logbook at End of Sector"],
["Sector 1 - 1st Tutorial Logbook", "Sector 1 - 2nd Tutorial Logbook", "Sector 1 - 3rd Tutorial Logbook", "Sector 1 - 4th Tutorial Logbook", "Sector 1 - 5th Tutorial Logbook", "Sector 1 - Logbook in Used Materials Access", "Sector 1 - Logbook next to Ribbon", "Sector 1 - Logbook in Guard Post", "Sector 1 - Logbook near Machine Gun", "Sector 1 - Logbook at End of Sector", "Sector 1 - 1st Logbook near Poster", "Sector 1 - 2nd Logbook near Poster", "Sector 1 - 3rd Logbook near Poster", "Sector 1 - 4th Logbook near Poster", "Sector 1 - Logbook near Supercharge"],
["Sector 2 - 1st Logbook at Start", "Sector 2 - 2nd Logbook at Start", "Sector 2 - 3rd Logbook at Start", "Sector 2 - 4th Logbook at Start", "Sector 2 - 5th Logbook at Start", "Sector 2 - 6th Logbook at Start", "Sector 2 - Logbook Left of Breakable Wall", "Sector 2 - Logbook Right of Breakable Wall", "Sector 2 - Logbook in Medical Access", "Sector 2 - 2nd Logbook Near Checkpoint", "Sector 2 - Logbook Near 1st Terminal", "Sector 2 - 1st Logbook Near Checkpoint", "Sector 2 - Logbook at Top of Medical Access", "Sector 2 - Logbook in Break Room", "Sector 2 - 1st Logbook Near Poster", "Sector 2 - 2nd Logbook Near Poster"],
["Sector 3 - Logbook at Start", "Sector 3 - Logbook in Software Development", "Sector 3 - 1st Logbook Left of Ribbon", "Sector 3 - 2nd Logbook Left of Ribbon", "Sector 3 - Logbook near Ceiling Blits", "Sector 3 - Logbook in Outdoors Section", "Sector 3 - 1st Logbook near Armor Upgrade", "Sector 3 - 2nd Logbook near Armor Upgrade", "Sector 3 - 1st Komato Logbook", "Sector 3 - 2nd Komato Logbook", "Sector 3 - 3rd Komato Logbook", "Sector 3 - 4th Komato Logbook", "Sector 3 - 1st Logbook near End of Sector", "Sector 3 - 2nd Logbook near End of Sector", "Sector 3 - Logbook at Right of Software Development", "Sector 3 - 1st Logbook behind Secured Doors", "Sector 3 - 2nd Logbook behind Secured Doors", "Sector 3 - Logbook near Poster"],
["Sector 4 - Logbook at Start", "Sector 4 - Logbook in Shaft above Secured Doors", "Sector 4 - Logbook toward Right Terminal", "Sector 4 - Logbook near Left Terminal", "Sector 4 - Logbook near Ribbon", "Sector 4 - Logbook near Reactor Core Elevator", "Sector 4 - 1st Logbook after Reactor Door", "Sector 4 - 2nd Logbook after Reactor Door", "Sector 4 - Logbook near End", "Sector 4 - Logbook Behind Breakable Wall at Start", "Sector 4 - Logbook near Main Storage Shredders", "Sector 4 - Logbook in Guard Post above Secured Doors", "Sector 4 - Logbook near Poster"],
["Sector 5 - Logbook in Incoming Goods", "Sector 5 - Logbook in Komato Assault Carrier", "Sector 5 - 1st Logbook near Left Terminal", "Sector 5 - 2nd Logbook near Left Terminal", "Sector 5 - Logbook at Bottom of Central Ventilation Shaft", "Sector 5 - 1st Logbook near Floor 3 Terminal", "Sector 5 - 2nd Logbook near Floor 3 Terminal", "Sector 5 - Logbook below Jump Upgrade", "Sector 5 - Logbook below Poster", "Sector 5 - Logbook before Final Elevator"],
["Sector 6 - Logbook next to Ventilation Shocksplinter", "Sector 6 - Logbook next to First Assassin", "Sector 6 - Logbook in Neoweapons Research Bottom", "Sector 6 - 1st Logbook after Secured Elevator Door", "Sector 6 - 2nd Logbook after Secured Elevator Door", "Sector 6 - Logbook next to Second Assassin", "Sector 6 - 1st Logbook near Supercharge", "Sector 6 - 2nd Logbook near Supercharge", "Sector 6 - 3rd Logbook near Supercharge", "Sector 6 - Logbook near End of Sector", "Sector 6 - Logbook next to Poster"],
["Sector 7 - Logbook at Start of Sector", "Sector 7 - Logbook in Ventilation near Start", "Sector 7 - Logbook before Exotic Technology Access", "Sector 7 - 1st Logbook in Armory", "Sector 7 - 2nd Logbook in Armory", "Sector 7 - 3rd Logbook in Armory", "Sector 7 - 1st Logbook on Platforms above Database Terminal", "Sector 7 - 2nd Logbook on Platforms above Database Terminal", "Sector 7 - Logbook near Internal Security Terminal", "Sector 7 - Logbook next to Hatch Terminal", "Sector 7 - Logbook near Komato Ship Exit", "Sector 7 - 1st Logbook after Rooftops", "Sector 7 - Logbook next to Teleporter at End of Sector", "Sector 7 - Logbook on Balcony next to Teleporter after Rooftops", "Sector 7 - Logbook next to CFIS", "Sector 7 - 1st Logbook in Top Left of Komato Ship", "Sector 7 - 2nd Logbook in Top Left of Komato Ship", "Sector 7 - 1st Logbook near Poster", "Sector 7 - 2nd Logbook near Poster", "Sector 7 - 1st Logbook in Crackers' Hideout", "Sector 7 - 2nd Logbook in Crackers' Hideout", "Sector 7 - 3rd Logbook in Crackers' Hideout", "Sector 7 - AREYOUSERIOUS Logbook Left of Komato Ship Exit"],
["Sector 8 - Logbook at Start of Sector", "Sector 8 - Logbook before Collapsible Floor", "Sector 8 - Logbook Left of Second Annihilator", "Sector 8 - 1st Logbook near Trapmine", "Sector 8 - 2nd Logbook near Trapmine", "Sector 8 - Logbook Right of Second Annihilator", "Sector 8 - Logbook near Ribbon", "Sector 8 - Logbook before Phantom Hammer Strike", "Sector 8 - Logbook near Armor Upgrade", "Sector 8 - Logbook next to Annihilator Beta Terminal", "Sector 8 - Logbook below Final Annihilator", "Sector 8 - Logbook above Final Annihilator", "Sector 8 - Logbook next to Staff Storage Teleporter", "Sector 8 - Logbook near Poster", "Sector 8 - Logbook at Right of Recreation"],
["Sector 9 - Logbook at Start", "Sector 9 - Logbook Right of Start", "Sector 9 - Logbook at Right of Bulkhead Area", "Sector 9 - Logbook at Top of Bulkhead Area", "Sector 9 - 1st Logbook near Assassin below Poster", "Sector 9 - 2nd Logbook near Assassin below Poster", "Sector 9 - Logbook near Break Room Weapon Station", "Sector 9 - Logbook above Shaft Leading to Bunker", "Sector 9 - 1st Logbook Outside Bunker", "Sector 9 - 2nd Logbook Outside Bunker", "Sector 9 - 1st Logbook in Bunker", "Sector 9 - 2nd Logbook in Bunker", "Sector 9 - 3rd Logbook in Bunker", "Sector 9 - Logbook next to Banana Gun", "Sector 9 - Logbook behind Secured Doors in Bunker", "Sector 9 - Logbook Outside Deep Sector", "Sector 9 - 1st Logbook in Deep Sector", "Sector 9 - 2nd Logbook in Deep Sector", "Sector 9 - 3rd Logbook in Deep Sector"],
["Sector X - Logbook near Start", "Sector X - 1st Logbook below First Elevator", "Sector X - 2nd Logbook below First Elevator", "Sector X - 1st Logbook near Megacore", "Sector X - 2nd Logbook near Megacore", "Sector X - 3rd Logbook near Megacore", "Sector X - Logbook to Right of Megacore", "Sector X - Logbook before Asha", "Sector X - 1st Logbook Left of Top of First Elevator", "Sector X - 2nd Logbook Left of Top of First Elevator", "Sector X - Logbook to Right of First Elevator", "Sector X - Logbook near Annihilator Beta", "Sector X - Logbook before Final Climb", "Sector X - 1st Logbook in Final Area", "Sector X - 2nd Logbook in Final Area", "Sector X - 3rd Logbook in Final Area", "Sector X - 4th Logbook in Final Area", "Sector X - 1st Logbook near Final Elevator", "Sector X - 2nd Logbook near Final Elevator", "Sector X - 3rd Logbook near Final Elevator", "Sector X - 4th Logbook near Final Elevator", "Sector X - Logbook across Large Gap near Start", "Sector X - 1st Logbook near Maximum Charge Terminal", "Sector X - 2nd Logbook near Maximum Charge Terminal", "Sector X - 3rd Logbook near Maximum Charge Terminal"],
["Sector Y - 1st Logbook Right of Start", "Sector Y - 2nd Logbook Right of Start", "Sector Y - 3rd Logbook Right of Start", "Sector Y - 4th Logbook Right of Start", "Sector Y - 5th Logbook Right of Start", "Sector Y - Logbook in Used Materials Access", "Sector Y - Logbook above Last Elevator", "Sector Y - Left of Last Elevator", "Sector Y - Logbook Right of Last Elevator", "Sector Y - Logbook at End of Sector", "Sector Y - 1st Logbook Left of Start", "Sector Y - 2nd Logbook Left of Start", "Sector Y - 3rd Logbook Left of Start", "Sector Y - 4th Logbook Left of Start", "Sector Y - Logbook near Poster of Doom"]
]

CrackBoxes: List[List[str]] = [
    ["Sector 2 - First Security Box", "Sector 2 - Security Box in Doctors' Offices", "Sector 2 - Security Box near Rocket Launcher", "Sector 2 - Security Box Next to Terminal", "Sector 2 - Security Box in Ventilation", "Sector 2 - Security Box in Storeroom", "Sector 2 - Security Box near Exit"],
    ["Sector 3 - Security Box 1 Left of Software Development", "Sector 3 - Security Box 2 Left of Software Development", "Sector 3 - Security Box in Storage A", "Sector 3 - Security Box 1 before Krotera", "Sector 3 - Security Box 2 before Krotera"],
    ["Sector 4 - Security Box"],
    ["Sector 5 - Security Box 1 in First Storeroom", "Sector 5 - Security Box 2 in First Storeroom", "Sector 5 - Security Box 3 in First Storeroom", "Sector 5 - Security Box in Second Storeroom", "Sector 5 - Security Box 1 near Jump Upgrade", "Sector 5 - Security Box 2 near Jump Upgrade"],
    ["Sector 6 - Security Box near Elevator", "Sector 6 - Security Box after Elevator Exit"],
    ["Sector 7 - Security Box 1 in Armory", "Sector 7 - Security Box 2 in Armory", "Sector 7 - Security Box below Ribbon"],
    ["Sector 8 - Security Box Next to Mine", "Sector 8 - Security Box next to Pitfall"],
    ["Sector 9 - Security Box 1 at Start", "Sector 9 - Security Box 2 at Start", "Sector 9 - Security Box Above Elevator Trap", "Sector 9 - Security Box near Bulkhead Lock A", "Sector 9 - Security Box in Guards' Quarters"],
    ["Sector X - Security Box near Start", "Sector X - Security Box near Annihilator Beta", "Sector X - Security Box in Final Climb"]
]

Overloads: List[List[str]] = [
    ["Sector 2 - Nano Overload in Medical Storage", "Sector 2 - Nano Overload in Security Station"],
    ["Sector 3 - Nano Overload after Storage Elevator"],
    ["Sector 4 - Nano Overload in Main Storage"],
    ["Sector 5 - Nano Overload in Storage Control Sideroom", "Sector 5 - Nano Overload in Classified Materials Analysis"],
    ["Sector 6 - Nano Overload at Bottom of Neoweapons Research"],
    ["Sector 7 - Nano Overload in Security Station", "Sector 7 - Nano Overload in Phantom Hammer Control"],
    ["Sector 8 - Nano Overload Left of Hammer Strike"],
    ["Sector 9 - Nano Overload in Megacore Research", "Sector 9 - Nano Overload near Start"],
    ["Sector X - Nano Overload in Final Climb", "Sector X - Nano Overload near Start"]
]

Sudden_Death: List[str] = [
    "Sector 1 - Sudden Death Sector Complete",
    "Sector 2 - Sudden Death Sector Complete",
    "Sector 3 - Sudden Death Sector Complete",
    "Sector 4 - Sudden Death Sector Complete",
    "Sector 5 - Sudden Death Sector Complete",
    "Sector 6 - Sudden Death Sector Complete",
    "Sector 7 - Sudden Death Sector Complete",
    "Sector 8 - Sudden Death Sector Complete",
    "Sector 9 - Sudden Death Sector Complete",
    "Sector X - Sudden Death Sector Complete"
]

Missile_Pony_X: List[str] = [
    "Sector 1 - Missile Pony X Clear",
    "Sector 2 - Missile Pony X Clear",
    "Sector 3 - Missile Pony X Clear",
    "Sector 4 - Missile Pony X Clear",
    "Sector 5 - Missile Pony X Clear",
    "Sector 6 - Missile Pony X Clear",
    "Sector 7 - Missile Pony X Clear",
    "Sector 8 - Missile Pony X Clear",
    "Sector 9 - Missile Pony X Clear",
    "Sector X - Missile Pony X Clear"
]

Checkpoints: List[str] = [
    "Sector 2 - Checkpoint",
    "Sector 3 - Checkpoint",
    "Sector 4 - Checkpoint",
    "Sector 5 - Checkpoint",
    "Sector 6 - Checkpoint",
    "Sector 7 - First Checkpoint",
    "Sector 7 - Second Checkpoint",
    "Sector 8 - Checkpoint",
    "Sector 9 - First Checkpoint",
    "Sector 9 - Second Checkpoint",
    "Sector X - First Checkpoint",
    "Sector X - Second Checkpoint"
]

Scrambler = "Sector 6 - Yukabacera's Scrambler"

Kills_Bosses: List[str] = [
    "Sector 3 - Kill Tasen Elite Krotera",  #95
    "Sector 9 - Kill Komato Annihilator Iosa",  #720
    "Sector X - Kill Komato Assassin Asha",  #755
    "Sector X - Kill Komato General Tor",  #798
    "Sector 7 - Destroy Komato Sentinel Proxima", #915
    "Sector 6 - Kill Tasen Soldier Yukabacera", #276
    "Sector 5 - Defeat Komato Assassin Asha", # 916
]

NORMAL: int = 5
HARD: int = 4
Kills_Scouts: List[tuple[int, str, str, int]] = [ # ID, Name, Region, Difficulty
    (1, "Sector 1 - Kill Tasen Scout Tuva", RegNames.Sector1_Main[0], NORMAL),
    (2, "Sector 1 - Kill Tasen Scout Ogrensie Tayu", RegNames.Sector1_Main[1], NORMAL),
    (3, "Sector 1 - Kill Tasen Scout Favi Savakrie", RegNames.Sector1_Main[1], NORMAL),
    (4, "Sector 1 - Kill Tasen Scout Zonrak", RegNames.Sector1_Main[1], HARD),
    (5, "Sector 1 - Kill Tasen Scout Xutei", RegNames.Sector1_Main[1], NORMAL),
    (8, "Sector 1 - Kill Tasen Scout Lofeito Hel", RegNames.Sector1_Main[1], HARD),
    (9, "Sector 1 - Kill Tasen Scout Shohaka", RegNames.Sector1_Main[1], NORMAL),
    (10, "Sector 1 - Kill Tasen Scout Uzon", RegNames.Sector1_Main[1], NORMAL),
    (12, "Sector 1 - Kill Tasen Scout Jao Viy", RegNames.Sector1_Side[1], NORMAL),
    (13, "Sector 1 - Kill Tasen Scout Sunsak", RegNames.Sector1_Main[3], NORMAL),
    (14, "Sector 1 - Kill Tasen Scout Mari", RegNames.Sector1_Main[3], NORMAL),
    (15, "Sector 1 - Kill Tasen Scout Fahel", RegNames.Sector1_Main[3], HARD),
    (23, "Sector 2 - Kill Tasen Scout Sasjusa", RegNames.Sector2_Main[2], NORMAL),
    (25, "Sector 2 - Kill Tasen Scout Grenkaitu", RegNames.Sector2_Main[2], HARD),
    (26, "Sector 2 - Kill Tasen Scout Saetor", RegNames.Sector2_Main[2], NORMAL),
    (27, "Sector 2 - Kill Tasen Scout Tei Faratie", RegNames.Sector2_Main[2], HARD),
    (29, "Sector 2 - Kill Tasen Scout Yuyu", RegNames.Sector2_Main[2], NORMAL),
    (30, "Sector 2 - Kill Tasen Scout Asdel", RegNames.Sector2_Main[2], NORMAL),
    (31, "Sector 2 - Kill Tasen Scout Kepaktoh", RegNames.Sector2_Main[2], NORMAL),
    (32, "Sector 2 - Kill Tasen Scout Bulei", RegNames.Sector2_Main[2], NORMAL),
    (33, "Sector 2 - Kill Tasen Scout Cobu", RegNames.Sector2_Main[3], NORMAL),
    (37, "Sector 2 - Kill Tasen Scout Wakro", RegNames.Sector2_Main[4], HARD),
    (38, "Sector 2 - Kill Tasen Scout Quhtei", RegNames.Sector2_Main[4], NORMAL),
    (39, "Sector 2 - Kill Tasen Scout Yah Rieba", RegNames.Sector2_Side[1], HARD),
    (42, "Sector 2 - Kill Tasen Scout Elipera", RegNames.Sector2_Main[5], NORMAL),
    (43, "Sector 2 - Kill Tasen Scout Zege Ba", RegNames.Sector2_Main[5], NORMAL),
    (45, "Sector 2 - Kill Tasen Scout Greno", RegNames.Sector2_Main[6], NORMAL),
    (52, "Sector 3 - Kill Tasen Scout Yankaio", RegNames.Sector3_Side[2], NORMAL),
    (53, "Sector 3 - Kill Tasen Scout Berge Ansho", RegNames.Sector3_Side[0], HARD),
    (54, "Sector 3 - Kill Tasen Scout Yisaktu", RegNames.Sector3_Side[0], NORMAL),
    (59, "Sector 3 - Kill Tasen Scout Hemsarier Izoni", RegNames.Sector3_Main[0], HARD),
    (60, "Sector 3 - Kill Tasen Scout Zonotuca", RegNames.Sector3_Main[0], NORMAL),
    (62, "Sector 3 - Kill Tasen Scout Xuribeyi", RegNames.Sector3_Main[1], NORMAL),
    (67, "Sector 3 - Kill Tasen Scout Hauk Viqu", RegNames.Sector3_Main[1], NORMAL),
    (68, "Sector 3 - Kill Tasen Scout Waktuke Zo", RegNames.Sector3_Main[1], HARD),
    (69, "Sector 3 - Kill Tasen Scout Emmae", RegNames.Sector3_Main[1], NORMAL),
    (72, "Sector 3 - Kill Tasen Scout Hasto", RegNames.Sector3_Main[1], NORMAL),
    (74, "Sector 3 - Kill Tasen Scout Jati", RegNames.Sector3_Main[1], NORMAL),
    (78, "Sector 3 - Kill Tasen Scout Siefa", RegNames.Sector3_Main[1], NORMAL),
    (79, "Sector 3 - Kill Tasen Scout Mawa Yae", RegNames.Sector3_Main[1], NORMAL),
    (80, "Sector 3 - Kill Tasen Scout Zonhelico", RegNames.Sector3_Main[1], NORMAL),
    (81, "Sector 3 - Kill Tasen Scout Zesie", RegNames.Sector3_Side[9], HARD),
    (82, "Sector 3 - Kill Tasen Scout Hawu", RegNames.Sector3_Side[9], NORMAL),
    (84, "Sector 3 - Kill Tasen Scout Heseilo", RegNames.Sector3_Main[1], NORMAL),
    (88, "Sector 3 - Kill Tasen Scout Zongeas", RegNames.Sector3_Main[1], NORMAL),
    (98, "Sector 4 - Kill Tasen Scout Tiikatei", RegNames.Sector4_Main[0], NORMAL),
    (100, "Sector 4 - Kill Tasen Scout Haia", RegNames.Sector4_Super[0], NORMAL),
    (102, "Sector 4 - Kill Tasen Scout Ashdel Es", RegNames.Sector4_Super[0], NORMAL),
    (105, "Sector 4 - Kill Tasen Scout Mali", RegNames.Sector4_Main[0], HARD),
    (106, "Sector 4 - Kill Tasen Scout Saefa", RegNames.Sector4_Main[0], HARD),
    (107, "Sector 4 - Kill Tasen Scout Wugren", RegNames.Sector4_Main[0], HARD),
    (108, "Sector 4 - Kill Tasen Scout Pah Bai", RegNames.Sector4_Main[0], NORMAL),
    (111, "Sector 4 - Kill Tasen Scout Tiei", RegNames.Sector4_Super[2], NORMAL),
    (112, "Sector 4 - Kill Tasen Scout Yinaklas", RegNames.Sector4_Super[2], NORMAL),
    (116, "Sector 4 - Kill Tasen Scout Tidepaash Sho", RegNames.Sector4_Main[1], HARD),
    (117, "Sector 4 - Kill Tasen Scout Zerie Cahashem", RegNames.Sector4_Main[1], HARD),
    (120, "Sector 4 - Kill Tasen Scout Hem Li", RegNames.Sector4_Main[1], NORMAL),
    (121, "Sector 4 - Kill Tasen Scout Vajagren", RegNames.Sector4_Main[1], NORMAL),
    (123, "Sector 4 - Kill Tasen Scout Detorpe Voe", RegNames.Sector4_Main[1], NORMAL),
    (124, "Sector 4 - Kill Tasen Scout Au Xutor", RegNames.Sector4_Main[1], NORMAL),
    (125, "Sector 4 - Kill Tasen Scout Rakaiwu", RegNames.Sector4_Main[1], NORMAL),
    (128, "Sector 4 - Kill Tasen Scout Torkai An", RegNames.Sector4_Main[2], NORMAL),
    (129, "Sector 4 - Kill Tasen Scout Rayah", RegNames.Sector4_Main[2], NORMAL),
    (130, "Sector 4 - Kill Tasen Scout Ke Fakera", RegNames.Sector4_Main[2], NORMAL),
    (134, "Sector 4 - Kill Tasen Scout Hastuwate", RegNames.Sector4_Main[3], NORMAL),
    (135, "Sector 4 - Kill Tasen Scout Malei Besha", RegNames.Sector4_Main[3], HARD),
    (138, "Sector 4 - Kill Tasen Scout Saegren Ta", RegNames.Sector4_Main[3], HARD),
    (139, "Sector 4 - Kill Tasen Scout Asti", RegNames.Sector4_Main[3], NORMAL),
    (140, "Sector 4 - Kill Tasen Scout Xuotta", RegNames.Sector4_Main[3], NORMAL),
    (141, "Sector 4 - Kill Tasen Scout Sunhem", RegNames.Sector4_Main[3], NORMAL),
    (146, "Sector 4 - Kill Tasen Scout Del Bacoisun", RegNames.Sector4_Main[5], NORMAL),
    (147, "Sector 4 - Kill Tasen Scout Ja Sha", RegNames.Sector4_Main[5], NORMAL),
    (148, "Sector 4 - Kill Tasen Scout Yaze", RegNames.Sector4_Main[5], NORMAL),
    (157, "Sector 5 - Kill Tasen Scout Rorak Viamae", RegNames.Sector5_Main[0], NORMAL),
    (159, "Sector 5 - Kill Tasen Scout Yriema", RegNames.Sector5_Main[0], NORMAL),
    (160, "Sector 5 - Kill Tasen Scout Askeiota", RegNames.Sector5_Main[0], NORMAL),
    (161, "Sector 5 - Kill Tasen Scout Roigren", RegNames.Sector5_Main[0], NORMAL),
    (163, "Sector 5 - Kill Tasen Scout Qurasha", RegNames.Sector5_Main[0], NORMAL),
    (164, "Sector 5 - Kill Tasen Scout Asei Xurai", RegNames.Sector5_Main[1], NORMAL),
    (165, "Sector 5 - Kill Tasen Scout Kaquosun", RegNames.Sector5_Main[1], NORMAL),
    (166, "Sector 5 - Kill Tasen Scout Helsak Losaeja", RegNames.Sector5_Main[1], NORMAL),
    (167, "Sector 5 - Kill Tasen Scout Rakjanio", RegNames.Sector5_Main[1], NORMAL),
    (168, "Sector 5 - Kill Tasen Scout Utoli", RegNames.Sector5_Main[1], NORMAL),
    (177, "Sector 5 - Kill Tasen Scout Pahesk Maeo", RegNames.Sector5_Main[2], NORMAL),
    (178, "Sector 5 - Kill Tasen Scout Saka", RegNames.Sector5_Main[2], NORMAL),
    (183, "Sector 5 - Kill Tasen Scout Klogrenu", RegNames.Sector5_Main[2], NORMAL),
    (184, "Sector 5 - Kill Tasen Scout Shouma", RegNames.Sector5_Main[2], NORMAL),
    (185, "Sector 5 - Kill Tasen Scout Aswu", RegNames.Sector5_Main[2], NORMAL),
    (186, "Sector 5 - Kill Tasen Scout Harieje", RegNames.Sector5_Main[2], NORMAL),
    (188, "Sector 5 - Kill Tasen Scout Torjaoto Saw", RegNames.Sector5_Main[2], NORMAL),
    (189, "Sector 5 - Kill Tasen Scout Berako", RegNames.Sector5_Main[2], NORMAL),
    (192, "Sector 5 - Kill Tasen Scout Zonrie", RegNames.Sector5_Main[2], NORMAL),
    (193, "Sector 5 - Kill Tasen Scout Elde Lipakotsun", RegNames.Sector5_Main[2], NORMAL),
    (194, "Sector 5 - Kill Tasen Scout Hel Wavate", RegNames.Sector5_Main[2], NORMAL),
    (201, "Sector 5 - Kill Tasen Scout Xugepei", RegNames.Sector5_Main[2], NORMAL),
    (208, "Sector 5 - Kill Tasen Scout Covayah", RegNames.Sector5_Poster[2], NORMAL),
    (210, "Sector 5 - Kill Tasen Scout Sunkeroi", RegNames.Sector5_Poster[2], NORMAL),
    (214, "Sector 5 - Kill Tasen Scout Aslova", RegNames.Sector5_Main[2], NORMAL),
    (220, "Sector 5 - Kill Tasen Scout Derak Jhokdel", RegNames.Sector5_Main[2], NORMAL),
    (223, "Sector 5 - Kill Tasen Scout Grenti Rokai", RegNames.Sector5_Main[2], NORMAL),
    (225, "Sector 5 - Kill Tasen Scout Yahpa", RegNames.Sector5_Main[2], NORMAL),
    (226, "Sector 5 - Kill Tasen Scout Niwakmae", RegNames.Sector5_Main[2], NORMAL),
    (228, "Sector 5 - Kill Tasen Scout Esgren Mae", RegNames.Sector5_Main[2], NORMAL),
    (229, "Sector 5 - Kill Tasen Scout Nidely", RegNames.Sector5_Main[2], NORMAL),
    (230, "Sector 5 - Kill Tasen Scout Anmaesk", RegNames.Sector5_Main[2], NORMAL),
    (232, "Sector 5 - Kill Tasen Scout Voetoro", RegNames.Sector5_Main[2], NORMAL),
    (233, "Sector 5 - Kill Tasen Scout Yies", RegNames.Sector5_Main[2], NORMAL),
    (235, "Sector 5 - Kill Tasen Scout Rasha", RegNames.Sector5_Main[2], HARD),
    (236, "Sector 5 - Kill Tasen Scout Rihauk", RegNames.Sector5_Main[2], NORMAL),
    (237, "Sector 5 - Kill Tasen Scout Toh Yuraiwu", RegNames.Sector5_Main[3], NORMAL),
    (242, "Sector 5 - Kill Tasen Scout Xuantura", RegNames.Sector5_Main[3], NORMAL),
    (243, "Sector 5 - Kill Tasen Scout Auta", RegNames.Sector5_Main[3], NORMAL),
    (247, "Sector 5 - Kill Tasen Scout Aumaba", RegNames.Sector5_Main[3], NORMAL),
    (248, "Sector 5 - Kill Tasen Scout Tosjael", RegNames.Sector5_Main[3], NORMAL),
    (249, "Sector 5 - Kill Tasen Scout Voesak Zoxu", RegNames.Sector5_Main[3], NORMAL),
    (252, "Sector 5 - Kill Tasen Scout Ka Namae", RegNames.Sector5_Main[4], NORMAL),
    (253, "Sector 5 - Kill Tasen Scout Caanwa", RegNames.Sector5_Main[4], NORMAL),
    (254, "Sector 5 - Kill Tasen Scout Jaope Te", RegNames.Sector5_Main[4], NORMAL),
    (258, "Sector 5 - Kill Tasen Scout Tohel", RegNames.Sector5_Main[4], NORMAL),

]
Kills_Soldiers: List[tuple[int, str, str, int]] = [
    (6, "Sector 1 - Kill Tasen Soldier Iri", RegNames.Sector1_Main[1], NORMAL),
    (7, "Sector 1 - Kill Tasen Soldier Elsa Haukti", RegNames.Sector1_Main[1], NORMAL),
    (11, "Sector 1 - Kill Tasen Soldier Tajasun", RegNames.Sector1_Main[1], NORMAL),
    (16, "Sector 1 - Kill Tasen Soldier Tusun Tuvaxu", RegNames.Sector1_Main[3], NORMAL),
    (22, "Sector 2 - Kill Tasen Soldier Cazedel", RegNames.Sector2_Main[2], NORMAL),
    (24, "Sector 2 - Kill Tasen Soldier Helmkai", RegNames.Sector2_Main[2], NORMAL),
    (28, "Sector 2 - Kill Tasen Soldier Yizepay", RegNames.Sector2_Main[2], NORMAL),
    (34, "Sector 2 - Kill Tasen Soldier Suntie", RegNames.Sector2_Main[3], NORMAL),
    (35, "Sector 2 - Kill Tasen Soldier Kari Lo", RegNames.Sector2_Main[3], HARD),
    (40, "Sector 2 - Kill Tasen Soldier Bupaqu", RegNames.Sector2_Side[1], NORMAL),
    (46, "Sector 2 - Kill Tasen Soldier Klexu", RegNames.Sector2_Main[6], NORMAL),
    (47, "Sector 2 - Kill Tasen Soldier Wusae", RegNames.Sector2_Side[5], NORMAL),
    (51, "Sector 3 - Kill Tasen Soldier Vateilika", RegNames.Sector3_Side[2], NORMAL),
    (55, "Sector 3 - Kill Tasen Soldier Naeman Jezo", RegNames.Sector3_Side[0], NORMAL),
    (56, "Sector 3 - Kill Tasen Soldier Vitohlei", RegNames.Sector3_Side[2], NORMAL),
    (57, "Sector 3 - Kill Tasen Soldier Hasu", RegNames.Sector3_Side[3], NORMAL),
    (58, "Sector 3 - Kill Tasen Soldier Coriwaqu", RegNames.Sector3_Side[3], NORMAL),
    (61, "Sector 3 - Kill Tasen Soldier Quburu Mari", RegNames.Sector3_Main[1], NORMAL),
    (64, "Sector 3 - Kill Tasen Soldier Zonohasha", RegNames.Sector3_Main[1], HARD),
    (65, "Sector 3 - Kill Tasen Soldier An Wak", RegNames.Sector3_Main[1], NORMAL),
    (70, "Sector 3 - Kill Tasen Soldier Waquhes", RegNames.Sector3_Main[1], HARD),
    (71, "Sector 3 - Kill Tasen Soldier Grenuti", RegNames.Sector3_Main[1], NORMAL),
    (75, "Sector 3 - Kill Tasen Soldier Yabaturaibu", RegNames.Sector3_Main[1], NORMAL),
    (77, "Sector 3 - Kill Tasen Soldier Cetor Fei", RegNames.Sector3_Main[1], HARD),
    (85, "Sector 3 - Kill Tasen Soldier Saenanita", RegNames.Sector3_Main[1], NORMAL),
    (86, "Sector 3 - Kill Tasen Soldier Jao Genio", RegNames.Sector3_Main[1], NORMAL),
    (90, "Sector 3 - Kill Tasen Soldier Maeja", RegNames.Sector3_Main[3], NORMAL),
    (97, "Sector 4 - Kill Tasen Soldier Esem Sie", RegNames.Sector4_Main[0], NORMAL),
    (101, "Sector 4 - Kill Tasen Soldier Grenka", RegNames.Sector4_Super[0], NORMAL),
    (103, "Sector 4 - Kill Tasen Soldier Hemgren", RegNames.Sector4_Super[0], HARD),
    (104, "Sector 4 - Kill Tasen Soldier Sharaiqy", RegNames.Sector4_Main[0], NORMAL),
    (109, "Sector 4 - Kill Tasen Soldier Hassjawak", RegNames.Sector4_Main[0], HARD),
    (110, "Sector 4 - Kill Tasen Soldier Zetirie", RegNames.Sector4_Main[0], NORMAL),
    (113, "Sector 4 - Kill Tasen Soldier Tilohauk", RegNames.Sector4_Main[1], NORMAL),
    (114, "Sector 4 - Kill Tasen Soldier Zebeli", RegNames.Sector4_Main[1], HARD),
    (115, "Sector 4 - Kill Tasen Soldier Ber Viketo", RegNames.Sector4_Main[1], NORMAL),
    (118, "Sector 4 - Kill Tasen Soldier Uria", RegNames.Sector4_Main[1], NORMAL),
    (119, "Sector 4 - Kill Tasen Soldier Yahwak", RegNames.Sector4_Main[1], NORMAL),
    (126, "Sector 4 - Kill Tasen Soldier Otelcau", RegNames.Sector4_Main[2], HARD),
    (131, "Sector 4 - Kill Tasen Soldier Jhoktai", RegNames.Sector4_Main[2], NORMAL),
    (133, "Sector 4 - Kill Tasen Soldier Ribe Ayah", RegNames.Sector4_Main[3], NORMAL),
    (137, "Sector 4 - Kill Tasen Soldier Rafajena", RegNames.Sector4_Main[3], NORMAL),
    (142, "Sector 4 - Kill Tasen Soldier Delderohas", RegNames.Sector4_Main[3], NORMAL),
    (144, "Sector 4 - Kill Tasen Soldier Payte", RegNames.Sector4_Poster[0], NORMAL),
    (145, "Sector 4 - Kill Tasen Soldier Xuaroika", RegNames.Sector4_Poster[0], NORMAL),
    (149, "Sector 4 - Kill Tasen Soldier Grenrahauk", RegNames.Sector4_Main[4], NORMAL),
    (150, "Sector 4 - Kill Tasen Soldier Emshata", RegNames.Sector4_Main[4], HARD),
    (156, "Sector 5 - Kill Tasen Soldier Visun", RegNames.Sector5_Main[0], NORMAL),
    (158, "Sector 5 - Kill Tasen Soldier Sunmawa", RegNames.Sector5_Main[0], NORMAL),
    (162, "Sector 5 - Kill Tasen Soldier Ibupay", RegNames.Sector5_Main[0], NORMAL),
    (169, "Sector 5 - Kill Tasen Soldier Kapah", RegNames.Sector5_Main[1], NORMAL),
    (170, "Sector 5 - Kill Tasen Soldier Paydepei", RegNames.Sector5_Main[1], NORMAL),
    (172, "Sector 5 - Kill Tasen Soldier Bevapa Riya", RegNames.Sector5_Main[1], NORMAL),
    (173, "Sector 5 - Kill Tasen Soldier Hel Rie", RegNames.Sector5_Main[1], NORMAL),
    (174, "Sector 5 - Kill Tasen Soldier Tisae", RegNames.Sector5_Main[1], NORMAL),
    (176, "Sector 5 - Kill Tasen Soldier Grenhasel", RegNames.Sector5_Main[2], NORMAL),
    (180, "Sector 5 - Kill Tasen Soldier Voe Vaksaera", RegNames.Sector5_Side[3], NORMAL),
    (181, "Sector 5 - Kill Tasen Soldier Helroihauk", RegNames.Sector5_Side[3], NORMAL),
    (187, "Sector 5 - Kill Tasen Soldier Kematasa", RegNames.Sector5_Main[2], NORMAL),
    (190, "Sector 5 - Kill Tasen Soldier Voesak", RegNames.Sector5_Main[2], NORMAL),
    (191, "Sector 5 - Kill Tasen Soldier Ikajhok Mae", RegNames.Sector5_Main[2], NORMAL),
    (196, "Sector 5 - Kill Tasen Soldier Yaeisako Sie", RegNames.Sector5_Main[2], HARD),
    (197, "Sector 5 - Kill Tasen Soldier Peroi", RegNames.Sector5_Main[2], NORMAL),
    (199, "Sector 5 - Kill Tasen Soldier Shofali", RegNames.Sector5_Main[2], HARD),
    (200, "Sector 5 - Kill Tasen Soldier Eswakzo", RegNames.Sector5_Main[2], NORMAL),
    (203, "Sector 5 - Kill Tasen Soldier Besaeti", RegNames.Sector5_Poster[1], NORMAL),
    (204, "Sector 5 - Kill Tasen Soldier Ti Ce", RegNames.Sector5_Poster[1], NORMAL),
    (206, "Sector 5 - Kill Tasen Soldier Xueshastu", RegNames.Sector5_Poster[2], NORMAL),
    (215, "Sector 5 - Kill Tasen Soldier Sakhas", RegNames.Sector5_Main[2], NORMAL),
    (218, "Sector 5 - Kill Tasen Soldier Roniba", RegNames.Sector5_Main[2], NORMAL),
    (219, "Sector 5 - Kill Tasen Soldier Otraktie", RegNames.Sector5_Main[2], HARD),
    (221, "Sector 5 - Kill Tasen Soldier Wu Mahro", RegNames.Sector5_Main[2], NORMAL),
    (222, "Sector 5 - Kill Tasen Soldier Yrak", RegNames.Sector5_Main[2], NORMAL),
    (227, "Sector 5 - Kill Tasen Soldier Embu", RegNames.Sector5_Ribbon, NORMAL),
    (231, "Sector 5 - Kill Tasen Soldier Wawaksie", RegNames.Sector5_Main[2], NORMAL),
    (234, "Sector 5 - Kill Tasen Soldier Del Je", RegNames.Sector5_Main[2], NORMAL),
    (239, "Sector 5 - Kill Tasen Soldier Zoniorak", RegNames.Sector5_Main[3], HARD),
    (240, "Sector 5 - Kill Tasen Soldier Japeito", RegNames.Sector5_Main[3], NORMAL),
    (244, "Sector 5 - Kill Tasen Soldier Ra Bexu", RegNames.Sector5_Main[3], NORMAL),
    (245, "Sector 5 - Kill Tasen Soldier Es Abersa", RegNames.Sector5_Main[3], NORMAL),
    (246, "Sector 5 - Kill Tasen Soldier Yahi", RegNames.Sector5_Main[3], NORMAL),
    (250, "Sector 5 - Kill Tasen Soldier Cece", RegNames.Sector5_Main[4], NORMAL),
    (255, "Sector 5 - Kill Tasen Soldier Ti Payra", RegNames.Sector5_Main[4], HARD),
    (256, "Sector 5 - Kill Tasen Soldier Yisie", RegNames.Sector5_Main[4], NORMAL),
    (257, "Sector 5 - Kill Tasen Soldier Zotakai", RegNames.Sector5_Main[4], NORMAL),
    (259, "Sector 5 - Kill Tasen Soldier Pakaze", RegNames.Sector5_Main[2], NORMAL),
    (266, "Sector 6 - Kill Tasen Soldier Asa Riesratu", RegNames.Sector6_Side[1], NORMAL),
    (268, "Sector 6 - Kill Tasen Soldier Rieesk", RegNames.Sector6_Side[1], NORMAL),
    (269, "Sector 6 - Kill Tasen Soldier Nicosaktor", RegNames.Sector6_Side[1], NORMAL),
    (271, "Sector 6 - Kill Tasen Soldier Hapa Famae", RegNames.Sector6_Main[0], HARD),
    (272, "Sector 6 - Kill Tasen Soldier Teitu", RegNames.Sector6_Side[1], NORMAL),
    (274, "Sector 6 - Kill Tasen Soldier Lite", RegNames.Sector6_Main[1], NORMAL),
    (275, "Sector 6 - Kill Tasen Soldier Dezo Ge", RegNames.Sector6_Main[1], NORMAL),
#    "Sector 6 - Kill Tasen Soldier Yukabacera",  # 276 See: Kills_Bosses
    (278, "Sector 6 - Kill Tasen Soldier Peio", RegNames.Sector6_Poster[1], NORMAL),
    (279, "Sector 6 - Kill Tasen Soldier Ro Nio", RegNames.Sector6_Side[8], NORMAL),
    (280, "Sector 6 - Kill Tasen Soldier Anli", RegNames.Sector6_Side[8], HARD),
    (281, "Sector 6 - Kill Tasen Soldier Delpah", RegNames.Sector6_Side[8], NORMAL),
    (285, "Sector 6 - Kill Tasen Soldier Bujaoro", RegNames.Sector6_Main[4], NORMAL),
    (286, "Sector 6 - Kill Tasen Soldier Nio Wunio", RegNames.Sector6_Main[4], NORMAL),
    (287, "Sector 6 - Kill Tasen Soldier Sharai Hage", RegNames.Sector6_Main[4], NORMAL),
    (288, "Sector 6 - Kill Tasen Soldier Jaofei Lotu", RegNames.Sector6_Main[4], NORMAL),
    (289, "Sector 6 - Kill Tasen Soldier Barosie", RegNames.Sector6_Main[4], NORMAL),
    (290, "Sector 6 - Kill Tasen Soldier Pei Ashridel", RegNames.Sector6_Main[4], NORMAL),
    (292, "Sector 6 - Kill Tasen Soldier Honadelot", RegNames.Sector6_Main[4], NORMAL),
    (293, "Sector 6 - Kill Tasen Soldier Xufei", RegNames.Sector6_Main[4], NORMAL),
    (294, "Sector 6 - Kill Tasen Soldier Ashihaso", RegNames.Sector6_Main[4], NORMAL),
    (296, "Sector 6 - Kill Tasen Soldier Tor Zelei", RegNames.Sector6_Main[4], NORMAL),
    (297, "Sector 6 - Kill Tasen Soldier Nazon Payhauk", RegNames.Sector6_Main[4], NORMAL),
    (299, "Sector 6 - Kill Tasen Soldier Maezon", RegNames.Sector6_Main[4], NORMAL),
    (300, "Sector 6 - Kill Tasen Soldier Xatie", RegNames.Sector6_Main[4], NORMAL),
    (301, "Sector 6 - Kill Tasen Soldier Qurawa", RegNames.Sector6_Main[4], NORMAL),
    (302, "Sector 6 - Kill Tasen Soldier Delsho", RegNames.Sector6_Main[4], NORMAL),
    (304, "Sector 6 - Kill Tasen Soldier Qunati", RegNames.Sector6_Main[4], NORMAL),
    (305, "Sector 6 - Kill Tasen Soldier Espay Hauk", RegNames.Sector6_Main[4], NORMAL),
    (306, "Sector 6 - Kill Tasen Soldier Riero", RegNames.Sector6_Main[4], NORMAL),
    (307, "Sector 6 - Kill Tasen Soldier Lixu", RegNames.Sector6_Side[11], HARD),
    (308, "Sector 6 - Kill Tasen Soldier Kasaot", RegNames.Sector6_Main[7], NORMAL),
    (309, "Sector 6 - Kill Tasen Soldier Copakri", RegNames.Sector6_Main[7], NORMAL),
    (310, "Sector 6 - Kill Tasen Soldier Unijero", RegNames.Sector6_Main[7], NORMAL),
    (311, "Sector 6 - Kill Tasen Soldier Zerak", RegNames.Sector6_Main[7], NORMAL),
    (316, "Sector 7 - Kill Tasen Soldier Kalo", RegNames.Sector7_Main[1], NORMAL),
    (317, "Sector 7 - Kill Tasen Soldier Hastohem", RegNames.Sector7_Main[1], NORMAL),
    (318, "Sector 7 - Kill Tasen Soldier Toshadel", RegNames.Sector7_Main[1], NORMAL),
    (319, "Sector 7 - Kill Tasen Soldier Hempei", RegNames.Sector7_Main[3], NORMAL),
    (321, "Sector 7 - Kill Tasen Soldier Shoca Bervoe", RegNames.Sector7_Main[3], NORMAL),
    (322, "Sector 7 - Kill Tasen Soldier Teini", RegNames.Sector7_Main[3], NORMAL),
    (323, "Sector 7 - Kill Tasen Soldier Emhauk", RegNames.Sector7_Main[3], NORMAL),
    (324, "Sector 7 - Kill Tasen Soldier Ritema", RegNames.Sector7_Main[3], NORMAL),
    (325, "Sector 7 - Kill Tasen Soldier Yutorha", RegNames.Sector7_Main[10], NORMAL),
    (326, "Sector 7 - Kill Tasen Soldier Ifei", RegNames.Sector7_Main[10], HARD),
    (327, "Sector 7 - Kill Tasen Soldier Mapak", RegNames.Sector7_Main[10], NORMAL),
    (328, "Sector 7 - Kill Tasen Soldier Viride", RegNames.Sector7_Main[10], NORMAL),
    (330, "Sector 7 - Kill Tasen Soldier Niowaklo", RegNames.Sector7_Main[10], NORMAL),
]
Kills_Commanders: List[tuple[int, str, str, int]] = [
    (21, "Sector 2 - Kill Tasen Commander Shahauk Hasja", RegNames.Sector2_Side[0], NORMAL),
    (36, "Sector 2 - Kill Tasen Commander Jage", RegNames.Sector2_Main[3], NORMAL),
    (41, "Sector 2 - Kill Tasen Commander Matoh Feiwaktor", RegNames.Sector2_Main[5], NORMAL),
    (63, "Sector 3 - Kill Tasen Commander Taasjasak", RegNames.Sector3_Side[6], NORMAL),
    (66, "Sector 3 - Kill Tasen Commander Lohauk Mae", RegNames.Sector3_Main[1], NORMAL),
    (73, "Sector 3 - Kill Tasen Commander Falo", RegNames.Sector3_Main[1], HARD),
    (76, "Sector 3 - Kill Tasen Commander Pahot", RegNames.Sector3_Main[1], NORMAL),
    (87, "Sector 3 - Kill Tasen Commander Quwao Sun", RegNames.Sector3_Main[1], NORMAL),
    (89, "Sector 3 - Kill Tasen Commander Cerixumah", RegNames.Sector3_Main[1], NORMAL),
    (96, "Sector 4 - Kill Tasen Commander Rakwu", RegNames.Sector4_Side[0], NORMAL),
    (99, "Sector 4 - Kill Tasen Commander Xaas", RegNames.Sector4_Main[0], NORMAL),
    (122, "Sector 4 - Kill Tasen Commander Paktei", RegNames.Sector4_Main[1], NORMAL),
    (136, "Sector 4 - Kill Tasen Commander Astoh Cacosaolo", RegNames.Sector4_Main[3], NORMAL),
    (143, "Sector 4 - Kill Tasen Commander Loroiyi", RegNames.Sector4_Main[3], NORMAL),
    (171, "Sector 5 - Kill Tasen Commander Otozobe Sha", RegNames.Sector5_Main[1], NORMAL),
    (179, "Sector 5 - Kill Tasen Commander Pahemli", RegNames.Sector5_Main[2], NORMAL),
    (182, "Sector 5 - Kill Tasen Commander Baqyi", RegNames.Sector5_Main[2], NORMAL),
    (195, "Sector 5 - Kill Tasen Commander Saqubu", RegNames.Sector5_Main[2], NORMAL),
    (198, "Sector 5 - Kill Tasen Commander Leige Raktor", RegNames.Sector5_Main[2], NORMAL),
    (202, "Sector 5 - Kill Tasen Commander Sunha", RegNames.Sector5_Main[2], NORMAL),
    (205, "Sector 5 - Kill Tasen Commander Eswa Kepah", RegNames.Sector5_Poster[2], NORMAL),
    (207, "Sector 5 - Kill Tasen Commander Liroto", RegNames.Sector5_Poster[2], NORMAL),
    (209, "Sector 5 - Kill Tasen Commander Haisak", RegNames.Sector5_Poster[2], NORMAL),
    (212, "Sector 5 - Kill Tasen Commander Zoyah", RegNames.Sector5_Poster[2], NORMAL),
    (216, "Sector 5 - Kill Tasen Commander Yukeca", RegNames.Sector5_Main[2], NORMAL),
    (224, "Sector 5 - Kill Tasen Commander As Xuvaksie", RegNames.Sector5_Main[2], NORMAL),
    (238, "Sector 5 - Kill Tasen Commander Na Mae", RegNames.Sector5_Main[3], NORMAL),
    (267, "Sector 6 - Kill Tasen Commander Yipaxu", RegNames.Sector6_Side[1], NORMAL),
    (270, "Sector 6 - Kill Tasen Commander Ka Del", RegNames.Sector6_Main[0], NORMAL),
    (273, "Sector 6 - Kill Tasen Commander Taelfei", RegNames.Sector6_Main[1], NORMAL),
    (277, "Sector 6 - Kill Tasen Commander Aysa", RegNames.Sector6_Poster[1], NORMAL),
    (282, "Sector 6 - Kill Tasen Commander Cesun", RegNames.Sector6_Side[8], NORMAL),
    (283, "Sector 6 - Kill Tasen Commander Bacatabu", RegNames.Sector6_Side[8], NORMAL),
    (284, "Sector 6 - Kill Tasen Commander Raigren", RegNames.Sector6_Main[4], NORMAL),
    (291, "Sector 6 - Kill Tasen Commander Mahxu", RegNames.Sector6_Main[4], NORMAL),
    (295, "Sector 6 - Kill Tasen Commander Zon Rihemco", RegNames.Sector6_Main[4], NORMAL),
    (298, "Sector 6 - Kill Tasen Commander Roja", RegNames.Sector6_Main[4], NORMAL),
    (303, "Sector 6 - Kill Tasen Commander Klash", RegNames.Sector6_Main[4], NORMAL),
    (312, "Sector 6 - Kill Tasen Commander Shofei", RegNames.Sector6_Main[7], NORMAL),
    (341, "Sector 8 - Kill Tasen Commander Roha Pexu", RegNames.Sector8_Side[2], NORMAL),
    (343, "Sector 8 - Kill Tasen Commander Nixuto Hastoh", RegNames.Sector8_Side[2], NORMAL),
    (344, "Sector 8 - Kill Tasen Commander Yahsie Kai", RegNames.Sector8_Main[2], NORMAL),
    (350, "Sector 8 - Kill Tasen Commander Deroi", RegNames.Sector8_Main[2], HARD),
    (351, "Sector 8 - Kill Tasen Commander Klasjaan", RegNames.Sector8_Main[3], NORMAL),
    (354, "Sector 8 - Kill Tasen Commander As Teisie", RegNames.Sector8_Main[3], NORMAL),
    (356, "Sector 8 - Kill Tasen Commander Em Sho", RegNames.Sector8_Main[3], NORMAL),
    (360, "Sector 8 - Kill Tasen Commander Xaxa Helni", RegNames.Sector8_Main[3], NORMAL),
    (361, "Sector 8 - Kill Tasen Commander Cosietu", RegNames.Sector8_Main[3], NORMAL),
]
Kills_Elites: List[tuple[int, str, str, int]] = [
    (44, "Sector 2 - Kill Tasen Elite Teira Sunjao", RegNames.Sector2_Side[3], NORMAL),
    (83, "Sector 3 - Kill Tasen Elite Jhokta", RegNames.Sector3_Side[9], NORMAL),
    (127, "Sector 4 - Kill Tasen Elite Xusha", RegNames.Sector4_Main[2], NORMAL),
    (132, "Sector 4 - Kill Tasen Elite Peihemfei", RegNames.Sector4_Main[2], NORMAL),
    (175, "Sector 5 - Kill Tasen Elite Vakrai", RegNames.Sector5_Main[1], NORMAL),
    (211, "Sector 5 - Kill Tasen Elite An Fa", RegNames.Sector5_Poster[2], NORMAL),
    (213, "Sector 5 - Kill Tasen Elite Dehemni Helpak", RegNames.Sector5_Poster[2], NORMAL),
    (217, "Sector 5 - Kill Tasen Elite Haspei", RegNames.Sector5_Main[2], NORMAL),
    (241, "Sector 5 - Kill Tasen Elite Kabe", RegNames.Sector5_Main[3], NORMAL),
    (251, "Sector 5 - Kill Tasen Elite Raber Shamah", RegNames.Sector5_Main[4], NORMAL),
    (320, "Sector 7 - Kill Tasen Elite Mavak", RegNames.Sector7_Main[3], NORMAL),
    (329, "Sector 7 - Kill Tasen Elite Jeka Berke", RegNames.Sector7_Main[10], NORMAL),
    (331, "Sector 7 - Kill Tasen Elite Coesta", RegNames.Sector7_Main[10], NORMAL),
    (332, "Sector 7 - Kill Tasen Elite Haukpei", RegNames.Sector7_Main[10], NORMAL),
    (333, "Sector 7 - Kill Tasen Elite Niquh", RegNames.Sector7_Main[10], NORMAL),
    (342, "Sector 8 - Kill Tasen Elite Vakeelta", RegNames.Sector8_Side[2], NORMAL),
    (345, "Sector 8 - Kill Tasen Elite Lei Ixuel", RegNames.Sector8_Main[2], HARD),
    (346, "Sector 8 - Kill Tasen Elite Hasconio", RegNames.Sector8_Main[2], NORMAL),
    (347, "Sector 8 - Kill Tasen Elite Jao Zejeni", RegNames.Sector8_Main[2], NORMAL),
    (348, "Sector 8 - Kill Tasen Elite Jaberi", RegNames.Sector8_Main[2], NORMAL),
    (349, "Sector 8 - Kill Tasen Elite Kavak", RegNames.Sector8_Main[2], NORMAL),
    (352, "Sector 8 - Kill Tasen Elite Xalei", RegNames.Sector8_Main[3], NORMAL),
    (353, "Sector 8 - Kill Tasen Elite Estepei", RegNames.Sector8_Main[3], NORMAL),
    (355, "Sector 8 - Kill Tasen Elite Xarajao", RegNames.Sector8_Main[3], NORMAL),
    (357, "Sector 8 - Kill Tasen Elite Torri", RegNames.Sector8_Main[3], NORMAL),
    (358, "Sector 8 - Kill Tasen Elite Mae Zeja", RegNames.Sector8_Main[3], NORMAL),
    (359, "Sector 8 - Kill Tasen Elite Pa Sjarak", RegNames.Sector8_Main[3], NORMAL),
    (366, "Sector 9 - Kill Tasen Elite Pahemsun", RegNames.Sector9_Main[3], NORMAL),
    (367, "Sector 9 - Kill Tasen Elite Haavi", RegNames.Sector9_Bulkhead, NORMAL),
]

Kills_Troopers: List[tuple[int, str, str, int]] = [
    (501, "Sector 3 - Kill Komato Trooper Zonharak", RegNames.Sector3_Main[2], NORMAL),
    (502, "Sector 3 - Kill Komato Trooper Siete", RegNames.Sector3_Main[2], NORMAL),
    (503, "Sector 3 - Kill Komato Trooper Xavi", RegNames.Sector3_Main[2], NORMAL),
    (504, "Sector 5 - Kill Komato Trooper Tortie", RegNames.Sector5_Main[0], NORMAL),
    (505, "Sector 5 - Kill Komato Trooper Wulei", RegNames.Sector5_Main[0], NORMAL),
    (506, "Sector 5 - Kill Komato Trooper Yaqupay", RegNames.Sector5_Main[0], NORMAL),
    (507, "Sector 5 - Kill Komato Trooper Mapei Pake", RegNames.Sector5_Main[1], NORMAL),
    (508, "Sector 5 - Kill Komato Trooper Naperak", RegNames.Sector5_Main[1], NORMAL),
    (509, "Sector 5 - Kill Komato Trooper Pa Essak", RegNames.Sector5_Main[1], NORMAL),
    (510, "Sector 5 - Kill Komato Trooper Xusun", RegNames.Sector5_Main[1], NORMAL),
    (511, "Sector 5 - Kill Komato Trooper Conaot", RegNames.Sector5_Main[1], NORMAL),
    (512, "Sector 5 - Kill Komato Trooper Ranibewu", RegNames.Sector5_Main[1], NORMAL),
    (513, "Sector 5 - Kill Komato Trooper Ja Losho", RegNames.Sector5_Main[1], NORMAL),
    (514, "Sector 5 - Kill Komato Trooper Esmah", RegNames.Sector5_Main[2], NORMAL),
    (517, "Sector 5 - Kill Komato Trooper Berem Niri", RegNames.Sector5_Main[2], HARD),
    (518, "Sector 5 - Kill Komato Trooper Elhas Valei", RegNames.Sector5_Main[2], NORMAL),
    (519, "Sector 5 - Kill Komato Trooper Dehemtor", RegNames.Sector5_Main[2], HARD),
    (520, "Sector 5 - Kill Komato Trooper Coro", RegNames.Sector5_Main[2], NORMAL),
    (522, "Sector 5 - Kill Komato Trooper Heltei", RegNames.Sector5_Main[2], HARD),
    (523, "Sector 5 - Kill Komato Trooper Zonjapako", RegNames.Sector5_Main[2], NORMAL),
    (524, "Sector 5 - Kill Komato Trooper Anzoma", RegNames.Sector5_Main[2], NORMAL),
    (525, "Sector 5 - Kill Komato Trooper Esa", RegNames.Sector5_Main[2], NORMAL),
    (526, "Sector 5 - Kill Komato Trooper Hasnio", RegNames.Sector5_Main[3], HARD),
    (527, "Sector 5 - Kill Komato Trooper Delpay", RegNames.Sector5_Main[3], NORMAL),
    (528, "Sector 5 - Kill Komato Trooper Hasa Vashode", RegNames.Sector5_Main[3], NORMAL),
    (529, "Sector 5 - Kill Komato Trooper Elbu", RegNames.Sector5_Main[3], NORMAL),
    (531, "Sector 5 - Kill Komato Trooper Sakteto", RegNames.Sector5_Main[4], NORMAL),
    (532, "Sector 5 - Kill Komato Trooper Berotpak", RegNames.Sector5_Main[4], NORMAL),
    (536, "Sector 6 - Kill Komato Trooper Bepei", RegNames.Sector6_Side[1], NORMAL),
    (537, "Sector 6 - Kill Komato Trooper Siero", RegNames.Sector6_Side[1], NORMAL),
    (538, "Sector 6 - Kill Komato Trooper Maoliem Buyah", RegNames.Sector6_Side[1], NORMAL),
    (539, "Sector 6 - Kill Komato Trooper Hastodel", RegNames.Sector6_Main[1], NORMAL),
    (540, "Sector 6 - Kill Komato Trooper Esvaksun", RegNames.Sector6_Main[1], NORMAL),
    (541, "Sector 6 - Kill Komato Trooper Ashber", RegNames.Sector6_Side[5], NORMAL),
    (542, "Sector 6 - Kill Komato Trooper Licehel Yavoe", RegNames.Sector6_Side[5], NORMAL),
    (543, "Sector 6 - Kill Komato Trooper Jahauk", RegNames.Sector6_Side[5], NORMAL),
    (544, "Sector 6 - Kill Komato Trooper Yasjulo", RegNames.Sector6_Poster[0], NORMAL),
    (545, "Sector 6 - Kill Komato Trooper Bede", RegNames.Sector6_Poster[0], NORMAL),
    (546, "Sector 6 - Kill Komato Trooper Zevitei", RegNames.Sector6_Main[4], NORMAL),
    (547, "Sector 6 - Kill Komato Trooper Qudel", RegNames.Sector6_Main[4], NORMAL),
    (548, "Sector 6 - Kill Komato Trooper Yeke", RegNames.Sector6_Main[4], NORMAL),
    (549, "Sector 6 - Kill Komato Trooper Sae", RegNames.Sector6_Main[4], NORMAL),
    (552, "Sector 6 - Kill Komato Trooper Butie Pahes", RegNames.Sector6_Main[4], NORMAL),
    (554, "Sector 6 - Kill Komato Trooper Sunwaktor", RegNames.Sector6_Main[4], NORMAL),
    (555, "Sector 6 - Kill Komato Trooper Teihasel", RegNames.Sector6_Main[12], NORMAL),
    (556, "Sector 6 - Kill Komato Trooper Rihauk Bewak", RegNames.Sector6_Main[12], HARD),
    (558, "Sector 6 - Kill Komato Trooper Bei Jexa", RegNames.Sector6_Main[12], NORMAL),
    (559, "Sector 6 - Kill Komato Trooper Shomahtu", RegNames.Sector6_Side[11], NORMAL),
    (560, "Sector 6 - Kill Komato Trooper Sakja", RegNames.Sector6_Side[11], NORMAL),
    (566, "Sector 7 - Kill Komato Trooper Shotupa", RegNames.Sector7_Main[1], NORMAL),
    (567, "Sector 7 - Kill Komato Trooper Fasiebe", RegNames.Sector7_Main[1], NORMAL),
    (568, "Sector 7 - Kill Komato Trooper Vakesha", RegNames.Sector7_Main[1], NORMAL),
    (569, "Sector 7 - Kill Komato Trooper Ashelhauk", RegNames.Sector7_Main[1], NORMAL),
    (571, "Sector 7 - Kill Komato Trooper Hember", RegNames.Sector7_Main[2], HARD),
    (572, "Sector 7 - Kill Komato Trooper Payroica", RegNames.Sector7_Main[2], NORMAL),
    (573, "Sector 7 - Kill Komato Trooper Yva Tataber", RegNames.Sector7_Main[1], NORMAL),
    (574, "Sector 7 - Kill Komato Trooper Auroba", RegNames.Sector7_Main[1], NORMAL),
    (576, "Sector 7 - Kill Komato Trooper Klas Ze", RegNames.Sector7_Main[1], HARD),
    (577, "Sector 7 - Kill Komato Trooper Jevak Delha", RegNames.Sector7_Main[1], NORMAL),
    (579, "Sector 7 - Kill Komato Trooper Raisak", RegNames.Sector7_Main[1], NORMAL),
    (580, "Sector 7 - Kill Komato Trooper Uusun", RegNames.Sector7_Main[1], NORMAL),
    (581, "Sector 7 - Kill Komato Trooper Shamakai", RegNames.Sector7_Main[3], NORMAL),
    (582, "Sector 7 - Kill Komato Trooper Hasetei", RegNames.Sector7_Main[3], NORMAL),
    (585, "Sector 7 - Kill Komato Trooper Valii Xuta", RegNames.Sector7_Main[3], HARD),
    (587, "Sector 7 - Kill Komato Trooper Nawa", RegNames.Sector7_Main[3], NORMAL),
    (589, "Sector 7 - Kill Komato Trooper Nihel", RegNames.Sector7_Main[4], NORMAL),
    (592, "Sector 7 - Kill Komato Trooper Ashniber", RegNames.Sector7_Main[6], NORMAL),
    (593, "Sector 7 - Kill Komato Trooper Tieropay", RegNames.Sector7_Main[6], HARD),
    (594, "Sector 7 - Kill Komato Trooper Saerak", RegNames.Sector7_Main[6], NORMAL),
    (595, "Sector 7 - Kill Komato Trooper Zehas", RegNames.Sector7_Main[5], NORMAL),
    (596, "Sector 7 - Kill Komato Trooper Payuka", RegNames.Sector7_Main[5], NORMAL),
    (597, "Sector 7 - Kill Komato Trooper Yahlei", RegNames.Sector7_Main[4], NORMAL),
    (599, "Sector 7 - Kill Komato Trooper Tei Torber", RegNames.Sector7_Main[4], NORMAL),
    (601, "Sector 7 - Kill Komato Trooper Namahot", RegNames.Sector7_Main[8], NORMAL),
    (603, "Sector 7 - Kill Komato Trooper Toba", RegNames.Sector7_Main[8], NORMAL),
    (606, "Sector 7 - Kill Komato Trooper Perie Viba", RegNames.Sector7_Main[8], NORMAL),
    (611, "Sector 7 - Kill Komato Trooper Peinioca", RegNames.Sector7_Main[9], NORMAL),
    (612, "Sector 7 - Kill Komato Trooper Yapakte Sabeze", RegNames.Sector7_Main[9], HARD),
    (613, "Sector 7 - Kill Komato Trooper Shavamah", RegNames.Sector7_Main[9], NORMAL),
    (626, "Sector 8 - Kill Komato Trooper Kairoi", RegNames.Sector8_Side[0], NORMAL),
    (627, "Sector 8 - Kill Komato Trooper Teloro", RegNames.Sector8_Side[0], NORMAL),
    (631, "Sector 8 - Kill Komato Trooper Maeri", RegNames.Sector8_Main[1], NORMAL),
    (632, "Sector 8 - Kill Komato Trooper Bewu", RegNames.Sector8_Main[1], NORMAL),
    (633, "Sector 8 - Kill Komato Trooper Grento Tei", RegNames.Sector8_Main[1], NORMAL),
    (634, "Sector 8 - Kill Komato Trooper Wakeske", RegNames.Sector8_Main[1], NORMAL),
    (637, "Sector 8 - Kill Komato Trooper Aheli", RegNames.Sector8_Main[2], HARD),
    (638, "Sector 8 - Kill Komato Trooper Teroma Rabuco", RegNames.Sector8_Main[2], NORMAL),
    (639, "Sector 8 - Kill Komato Trooper Buyi", RegNames.Sector8_Main[2], NORMAL),
    (642, "Sector 8 - Kill Komato Trooper Tohankai", RegNames.Sector8_Main[2], NORMAL),
    (643, "Sector 8 - Kill Komato Trooper Cotorni", RegNames.Sector8_Main[2], NORMAL),
    (644, "Sector 8 - Kill Komato Trooper Emhaja", RegNames.Sector8_Main[2], NORMAL),
    (645, "Sector 8 - Kill Komato Trooper Zokepei", RegNames.Sector8_Main[2], NORMAL),
    (646, "Sector 8 - Kill Komato Trooper Xusa Yu", RegNames.Sector8_Main[2], NORMAL),
    (649, "Sector 8 - Kill Komato Trooper Haukot", RegNames.Sector8_Main[3], NORMAL),
    (651, "Sector 8 - Kill Komato Trooper Yusak Jao", RegNames.Sector8_Main[3], NORMAL),
    (652, "Sector 8 - Kill Komato Trooper Torrabaya", RegNames.Sector8_Main[3], NORMAL),
    (654, "Sector 8 - Kill Komato Trooper Zonna", RegNames.Sector8_Main[3], NORMAL),
    (656, "Sector 8 - Kill Komato Trooper Xube", RegNames.Sector8_Main[3], NORMAL),
    (657, "Sector 8 - Kill Komato Trooper Esuvi", RegNames.Sector8_Main[3], NORMAL),
    (659, "Sector 8 - Kill Komato Trooper Toheska", RegNames.Sector8_Main[3], NORMAL), # The Dan one
    (666, "Sector 9 - Kill Komato Trooper Hemvi", RegNames.Sector9_Side[1], NORMAL),
    (667, "Sector 9 - Kill Komato Trooper Xao", RegNames.Sector9_Side[1], NORMAL),
    (668, "Sector 9 - Kill Komato Trooper Asfaroi", RegNames.Sector9_Side[1], NORMAL),
    (669, "Sector 9 - Kill Komato Trooper Bawa Natei", RegNames.Sector9_Main[0], NORMAL),
    (670, "Sector 9 - Kill Komato Trooper Haniri", RegNames.Sector9_Main[0], NORMAL),
    (673, "Sector 9 - Kill Komato Trooper Elhasan", RegNames.Sector9_Main[1], NORMAL),
    (674, "Sector 9 - Kill Komato Trooper Saewu", RegNames.Sector9_Main[1], NORMAL),
    (675, "Sector 9 - Kill Komato Trooper Zeca Paktubero", RegNames.Sector9_Main[1], NORMAL),
    (679, "Sector 9 - Kill Komato Trooper Yusae Behem", RegNames.Sector9_Main[3], NORMAL),
    (680, "Sector 9 - Kill Komato Trooper Voekasho", RegNames.Sector9_Main[3], NORMAL),
    (682, "Sector 9 - Kill Komato Trooper Zeberan", RegNames.Sector9_Main[3], NORMAL),
    (683, "Sector 9 - Kill Komato Trooper Payrie", RegNames.Sector9_Main[3], NORMAL),
    (684, "Sector 9 - Kill Komato Trooper Ohauk Wakrai", RegNames.Sector9_Main[3], HARD),
    (685, "Sector 9 - Kill Komato Trooper Saeta", RegNames.Sector9_Bulkhead[2], NORMAL),
    (686, "Sector 9 - Kill Komato Trooper Hasta", RegNames.Sector9_Main[3], HARD),
    (688, "Sector 9 - Kill Komato Trooper Feidesho", RegNames.Sector9_Main[3], NORMAL),
    (689, "Sector 9 - Kill Komato Trooper Zozenata Tofao", RegNames.Sector9_Main[3], NORMAL),
    (690, "Sector 9 - Kill Komato Trooper Nio Xebe", RegNames.Sector9_Main[3], NORMAL),
    (693, "Sector 9 - Kill Komato Trooper Mahesmae", RegNames.Sector9_Main[3], NORMAL),
    (694, "Sector 9 - Kill Komato Trooper Xa Decaa", RegNames.Sector9_Main[3], NORMAL),
    (695, "Sector 9 - Kill Komato Trooper Yao Wahem", RegNames.Sector9_Main[4], HARD),
    (696, "Sector 9 - Kill Komato Trooper Tushata", RegNames.Sector9_Main[4], HARD),
    (698, "Sector 9 - Kill Komato Trooper Kaiya", RegNames.Sector9_Main[4], NORMAL),
    (701, "Sector 9 - Kill Komato Trooper Baqu Ta", RegNames.Sector9_Main[6], NORMAL),
    (702, "Sector 9 - Kill Komato Trooper Astor", RegNames.Sector9_Main[6], NORMAL),
    (703, "Sector 9 - Kill Komato Trooper Delli", RegNames.Sector9_Side[14], NORMAL),
    (704, "Sector 9 - Kill Komato Trooper Mavatonio", RegNames.Sector9_Side[14], NORMAL),
    (705, "Sector 9 - Kill Komato Trooper Zontu", RegNames.Sector9_Main[4], NORMAL),
    (706, "Sector 9 - Kill Komato Trooper Fayati Sho", RegNames.Sector9_Main[5], NORMAL),
    (711, "Sector 9 - Kill Komato Trooper Keto", RegNames.Sector9_Side[9], NORMAL),
    (712, "Sector 9 - Kill Komato Trooper Saki Ro", RegNames.Sector9_Side[9], NORMAL),
    (721, "Sector X - Kill Komato Trooper Hasroi", RegNames.SectorX_Main[1], HARD),
    (722, "Sector X - Kill Komato Trooper Xuroi", RegNames.SectorX_Main[1], NORMAL),
    (725, "Sector X - Kill Komato Trooper Ottohas Sha", RegNames.SectorX_Main[1], NORMAL),
    (727, "Sector X - Kill Komato Trooper Nasatorai", RegNames.SectorX_Main[2], NORMAL),
    (731, "Sector X - Kill Komato Trooper Ba Waturi", RegNames.SectorX_Main[2], NORMAL),
    (733, "Sector X - Kill Komato Trooper Batasa", RegNames.SectorX_Core[1], NORMAL),
    (734, "Sector X - Kill Komato Trooper Yuta", RegNames.SectorX_Core[1], NORMAL),
    (735, "Sector X - Kill Komato Trooper Una", RegNames.SectorX_Core[1], NORMAL),
    (736, "Sector X - Kill Komato Trooper Fahasma", RegNames.SectorX_Core[1], HARD),
    (737, "Sector X - Kill Komato Trooper Zon Hemriesk", RegNames.SectorX_Core[1], NORMAL),
    (739, "Sector X - Kill Komato Trooper Ausu", RegNames.SectorX_Core[1], NORMAL),
    (740, "Sector X - Kill Komato Trooper Tetorni Hasot", RegNames.SectorX_Core[1], NORMAL),
    (741, "Sector X - Kill Komato Trooper Jexao Haasa", RegNames.SectorX_Core[1], HARD),
    (742, "Sector X - Kill Komato Trooper Shokaiya", RegNames.SectorX_Core[1], HARD),
    (743, "Sector X - Kill Komato Trooper Liquh Yirai", RegNames.SectorX_Core[1], NORMAL),
    (744, "Sector X - Kill Komato Trooper Mateii", RegNames.SectorX_Core[1], NORMAL),
    (746, "Sector X - Kill Komato Trooper Yahesk", RegNames.SectorX_Core[1], HARD),
    (747, "Sector X - Kill Komato Trooper Ni Hato", RegNames.SectorX_Core[1], NORMAL),
    (748, "Sector X - Kill Komato Trooper Buzon", RegNames.SectorX_Core[1], NORMAL),
    (749, "Sector X - Kill Komato Trooper Pean", RegNames.SectorX_Core[1], HARD),
    (752, "Sector X - Kill Komato Trooper Yuroi Kahel", RegNames.SectorX_Core[4], NORMAL),
    (753, "Sector X - Kill Komato Trooper Ateesto", RegNames.SectorX_Core[4], HARD),
    (757, "Sector X - Kill Komato Trooper Xusakya", RegNames.SectorX_Main[8], NORMAL),
    (758, "Sector X - Kill Komato Trooper Otber", RegNames.SectorX_Side[1], NORMAL),
    (759, "Sector X - Kill Komato Trooper Torash", RegNames.SectorX_Side[1], NORMAL),
    (760, "Sector X - Kill Komato Trooper Rai Ke", RegNames.SectorX_Main[12], NORMAL),
    (761, "Sector X - Kill Komato Trooper Yugewu Shasha", RegNames.SectorX_Main[12], HARD),
    (762, "Sector X - Kill Komato Trooper Zekailo", RegNames.SectorX_Main[12], NORMAL),
    (763, "Sector X - Kill Komato Trooper Tarixuro", RegNames.SectorX_Main[10], HARD),
    (765, "Sector X - Kill Komato Trooper Shaba", RegNames.SectorX_Main[10], NORMAL),
    (774, "Sector X - Kill Komato Trooper Yahra", RegNames.SectorX_Final[0], NORMAL),
    (775, "Sector X - Kill Komato Trooper Xuhauk Cozea", RegNames.SectorX_Final[0], NORMAL),
    (777, "Sector X - Kill Komato Trooper Xadelhauk", RegNames.SectorX_Final[0], NORMAL),
    (778, "Sector X - Kill Komato Trooper Tebusjua", RegNames.SectorX_Final[0], NORMAL),
    (779, "Sector X - Kill Komato Trooper Sha Vaemash", RegNames.SectorX_Final[0], NORMAL),
    (781, "Sector X - Kill Komato Trooper Yufei", RegNames.SectorX_Final[0], NORMAL),
    (784, "Sector X - Kill Komato Trooper Au Wuria", RegNames.SectorX_Side[4], NORMAL),
    (785, "Sector X - Kill Komato Trooper Tupei", RegNames.SectorX_Final[2], NORMAL),
    (786, "Sector X - Kill Komato Trooper Dejama", RegNames.SectorX_Final[2], NORMAL),
    (787, "Sector X - Kill Komato Trooper Kerohasel", RegNames.SectorX_Final[2], NORMAL),
    (788, "Sector X - Kill Komato Trooper Jaau", RegNames.SectorX_Final[2], NORMAL),
    (789, "Sector X - Kill Komato Trooper Satesja", RegNames.SectorX_Final[2], NORMAL),
    (790, "Sector X - Kill Komato Trooper Auzefei", RegNames.SectorX_Final[2], NORMAL),
    (791, "Sector X - Kill Komato Trooper Cati Ketosun", RegNames.SectorX_Final[3], NORMAL),
]
Kills_Berserkers: List[tuple[int, str, str, int]] = [
    (515, "Sector 5 - Kill Komato Berserker Zonio", RegNames.Sector5_Main[2], NORMAL),
    (516, "Sector 5 - Kill Komato Berserker Xarai", RegNames.Sector5_Main[2], NORMAL),
    (521, "Sector 5 - Kill Komato Berserker Hasmah", RegNames.Sector5_Main[2], NORMAL),
    (530, "Sector 5 - Kill Komato Berserker Vakalei", RegNames.Sector5_Main[4], NORMAL),
    (550, "Sector 6 - Kill Komato Berserker Toniterai", RegNames.Sector6_Main[4], NORMAL),
    (551, "Sector 6 - Kill Komato Berserker Hemesko", RegNames.Sector6_Main[4], NORMAL),
    (553, "Sector 6 - Kill Komato Berserker Tegesun", RegNames.Sector6_Main[4], NORMAL),
    (557, "Sector 6 - Kill Komato Berserker Losho", RegNames.Sector6_Main[12], NORMAL),
    (561, "Sector 6 - Kill Komato Berserker Xuge", RegNames.Sector6_Side[11], NORMAL),
    (570, "Sector 7 - Kill Komato Berserker Roive Besiena", RegNames.Sector7_Main[2], NORMAL),
    (575, "Sector 7 - Kill Komato Berserker Xutei", RegNames.Sector7_Main[1], HARD),
    (578, "Sector 7 - Kill Komato Berserker Ti Jhokro", RegNames.Sector7_Main[1], NORMAL),
    (584, "Sector 7 - Kill Komato Berserker Hauksha", RegNames.Sector7_Main[3], NORMAL),
    (588, "Sector 7 - Kill Komato Berserker Zondebaot", RegNames.Sector7_Main[3], NORMAL),
    (608, "Sector 7 - Kill Komato Berserker Saktoro", RegNames.Sector7_Main[9], NORMAL),
    (609, "Sector 7 - Kill Komato Berserker Teixato", RegNames.Sector7_Main[9], NORMAL),
    (610, "Sector 7 - Kill Komato Berserker Roquh", RegNames.Sector7_Main[9], NORMAL),
    (614, "Sector 7 - Kill Komato Berserker Ke Deyi", RegNames.Sector7_Main[9], NORMAL),
    (615, "Sector 7 - Kill Komato Berserker Saesie", RegNames.Sector7_Main[10], NORMAL),
    (616, "Sector 7 - Kill Komato Berserker Betorsa", RegNames.Sector7_Main[10], NORMAL),
    (617, "Sector 7 - Kill Komato Berserker Gevi", RegNames.Sector7_Main[10], HARD),
    (620, "Sector 7 - Kill Komato Berserker Coturie", RegNames.Sector7_Main[10], NORMAL),
    (628, "Sector 8 - Kill Komato Berserker Yubi", RegNames.Sector8_Side[1], NORMAL),
    (629, "Sector 8 - Kill Komato Berserker Saewa", RegNames.Sector8_Main[1], NORMAL),
    (630, "Sector 8 - Kill Komato Berserker Jao Otdel", RegNames.Sector8_Main[1], HARD),
    (635, "Sector 8 - Kill Komato Berserker Jali", RegNames.Sector8_Main[1], NORMAL),
    (641, "Sector 8 - Kill Komato Berserker Bunazo", RegNames.Sector8_Main[2], HARD),
    (647, "Sector 8 - Kill Komato Berserker Gekeelzo", RegNames.Sector8_Main[2], NORMAL),
    (648, "Sector 8 - Kill Komato Berserker Eri", RegNames.Sector8_Main[2], NORMAL),
    (650, "Sector 8 - Kill Komato Berserker Juibertei", RegNames.Sector8_Main[3], NORMAL),
    (653, "Sector 8 - Kill Komato Berserker Leisun Jeyu", RegNames.Sector8_Main[3], NORMAL),
    (655, "Sector 8 - Kill Komato Berserker Voe Vi", RegNames.Sector8_Main[3], NORMAL),
    (671, "Sector 9 - Kill Komato Berserker Vilokato", RegNames.Sector9_Main[0], NORMAL),
    (672, "Sector 9 - Kill Komato Berserker Litor", RegNames.Sector9_Main[1], NORMAL),
    (677, "Sector 9 - Kill Komato Berserker Sharaceti", RegNames.Sector9_Main[1], NORMAL),
    (678, "Sector 9 - Kill Komato Berserker Sie Esk", RegNames.Sector9_Main[1], NORMAL),
    (681, "Sector 9 - Kill Komato Berserker Au Rakrai", RegNames.Sector9_Main[3], NORMAL),
    (691, "Sector 9 - Kill Komato Berserker Licozon", RegNames.Sector9_Main[3], NORMAL),
    (697, "Sector 9 - Kill Komato Berserker Jefei", RegNames.Sector9_Main[4], NORMAL),
    (699, "Sector 9 - Kill Komato Berserker Li Sakel", RegNames.Sector9_Main[6], HARD),
    (700, "Sector 9 - Kill Komato Berserker Kahapa", RegNames.Sector9_Main[6], NORMAL),
    (707, "Sector 9 - Kill Komato Berserker Irai Helto", RegNames.Sector9_Main[9], NORMAL),
    (709, "Sector 9 - Kill Komato Berserker Varo", RegNames.Sector9_Side[9], NORMAL),
    (710, "Sector 9 - Kill Komato Berserker Auratoh", RegNames.Sector9_Side[9], NORMAL),
    (723, "Sector X - Kill Komato Berserker Livigren", RegNames.SectorX_Main[1], NORMAL),
    (724, "Sector X - Kill Komato Berserker Niodely", RegNames.SectorX_Main[1], HARD),
    (728, "Sector X - Kill Komato Berserker Voe Ikahas", RegNames.SectorX_Main[2], NORMAL),
    (738, "Sector X - Kill Komato Berserker Peterol", RegNames.SectorX_Core[1], NORMAL),
    (750, "Sector X - Kill Komato Berserker Cerisha", RegNames.SectorX_Core[1], NORMAL),
    (751, "Sector X - Kill Komato Berserker Tor Rosun", RegNames.SectorX_Core[4], NORMAL),
    (754, "Sector X - Kill Komato Berserker Roxayi", RegNames.SectorX_Core[5], NORMAL),
    (756, "Sector X - Kill Komato Berserker Baviem", RegNames.SectorX_Main[8], NORMAL),
    (764, "Sector X - Kill Komato Berserker Xubusak", RegNames.SectorX_Main[10], NORMAL),
    (766, "Sector X - Kill Komato Berserker Anbevi", RegNames.SectorX_Main[9], HARD),
    (767, "Sector X - Kill Komato Berserker Hariewu Cekai", RegNames.SectorX_Main[9], HARD),
    (768, "Sector X - Kill Komato Berserker Cosaeco", RegNames.SectorX_Main[9], NORMAL),
    (769, "Sector X - Kill Komato Berserker Qygren", RegNames.SectorX_Main[9], NORMAL),
    (770, "Sector X - Kill Komato Berserker Viramah", RegNames.SectorX_Main[9], NORMAL),
    (772, "Sector X - Kill Komato Berserker Tormaebu", RegNames.SectorX_Final[0], NORMAL),
    (773, "Sector X - Kill Komato Berserker Feirakotem", RegNames.SectorX_Final[0], NORMAL),
    (782, "Sector X - Kill Komato Berserker Bauni Ce", RegNames.SectorX_Final[1], NORMAL),
    (783, "Sector X - Kill Komato Berserker Vazonja", RegNames.SectorX_Final[1], NORMAL),
]
Kills_Beasts: List[tuple[int, str, str, int]] = [
    (583, "Sector 7 - Kill Komato Beast Yahli Saetoh", RegNames.Sector7_Main[3], HARD),
    (586, "Sector 7 - Kill Komato Beast Waktaka", RegNames.Sector7_Main[3], NORMAL),
    (590, "Sector 7 - Kill Komato Beast Debapa", RegNames.Sector7_Main[4], NORMAL),
    (591, "Sector 7 - Kill Komato Beast Bu Sha", RegNames.Sector7_Main[4], NORMAL),
    (598, "Sector 7 - Kill Komato Beast Pah Sunlonio", RegNames.Sector7_Main[4], HARD),
    (600, "Sector 7 - Kill Komato Beast Osaklas", RegNames.Sector7_Main[4], NORMAL),
    (602, "Sector 7 - Kill Komato Beast Jaoemni Rodel", RegNames.Sector7_Main[8], NORMAL),
    (604, "Sector 7 - Kill Komato Beast Payma Fagren", RegNames.Sector7_Main[8], NORMAL),
    (605, "Sector 7 - Kill Komato Beast Wurie", RegNames.Sector7_Main[8], NORMAL),
    (607, "Sector 7 - Kill Komato Beast Shatei", RegNames.Sector7_Main[8], HARD),
    (618, "Sector 7 - Kill Komato Beast Anvakta", RegNames.Sector7_Ribbon, NORMAL),
    (619, "Sector 7 - Kill Komato Beast Mahnio", RegNames.Sector7_Ribbon, NORMAL),
    (621, "Sector 7 - Kill Komato Beast Payjaux", RegNames.Sector7_Main[10], NORMAL),
    (676, "Sector 9 - Kill Komato Beast Lioma", RegNames.Sector9_Main[1], NORMAL),
    (692, "Sector 9 - Kill Komato Beast Tupei Mator", RegNames.Sector9_Main[9], HARD),
    (729, "Sector X - Kill Komato Beast Hassali", RegNames.SectorX_Main[2], HARD),
    (730, "Sector X - Kill Komato Beast Viri", RegNames.SectorX_Main[2], NORMAL),
    (732, "Sector X - Kill Komato Beast Yiyu Qyan", RegNames.SectorX_Main[2], NORMAL),
    (776, "Sector X - Kill Komato Beast Gejacora", RegNames.SectorX_Final[0], HARD),
    (780, "Sector X - Kill Komato Beast Auwak", RegNames.SectorX_Final[0], NORMAL),
]
Kills_Assassins: List[tuple[int, str, str]] = [
    (901, "Sector 6 - Defeat Komato Assassin in Neoweapons Storage", RegNames.Sector6_Main[3]),
    (902, "Sector 6 - Defeat Komato Assassin in Unused Storage", RegNames.Sector6_Main[6]),
    (903, "Sector 7 - Defeat Komato Assassin in Internal Security", RegNames.Sector7_Main[5]),
    (904, "Sector 7 - Defeat Komato Assassin in Phantom Hammer Control", RegNames.Sector7_Main[8]),
    (905, "Sector 9 - Defeat Komato Assassin in Elevator Trap", RegNames.Sector9_Main[2]),
    (906, "Sector 9 - Defeat Komato Assassin in Illegal Goods Storage", RegNames.Sector9_Poster[0]),
    (907, "Sector 9 - Defeat Komato Assassin in Megacore Research", RegNames.Sector9_Main[9]),
    (908, "Sector 9 - Defeat 1st Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (909, "Sector 9 - Defeat 2nd Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (910, "Sector 9 - Defeat 3rd Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (911, "Sector 9 - Defeat 4th Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (912, "Sector 9 - Defeat 5th Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (913, "Sector 9 - Defeat 6th Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9]),
    (914, "Sector 9 - Defeat 7th Komato Assassin in Deep Sector", RegNames.Sector9_Deep[9])
]
Kills_Annihilators: List[tuple[int, str, str]] = [
    (636, "Sector 8 - Kill Komato Annihilator Deltojaro", RegNames.Sector8_Main[2]),
    (640, "Sector 8 - Kill Komato Annihilator Helri Lo", RegNames.Sector8_Main[2]),
    (658, "Sector 8 - Kill Komato Annihilator Gerakka", RegNames.Sector8_Main[3]),
    (687, "Sector 9 - Kill Komato Annihilator Be Xuya", RegNames.Sector9_Main[3]),
    (708, "Sector 9 - Kill Komato Annihilator Yrie", RegNames.Sector9_Main[9]),
    (726, "Sector X - Kill Komato Annihilator Vasa", RegNames.SectorX_Main[1]),
    (745, "Sector X - Kill Komato Annihilator Siena", RegNames.SectorX_Core[1]),
    (771, "Sector X - Kill Komato Annihilator Saejao Buhastahel", RegNames.SectorX_Final[0]),
    (792, "Sector X - Kill Komato Annihilator Tubuvak Asna", RegNames.SectorX_Final[3]),
]

Kills_Sector_Z: List[str] = [
    "Sector Z - Kill 1 White Sphere",   # 801 -> 822
    "Sector Z - Kill 2 White Spheres",
    "Sector Z - Kill 3 White Spheres",
    "Sector Z - Kill 4 White Spheres",
    "Sector Z - Kill 5 White Spheres",
    "Sector Z - Kill 6 White Spheres",
    "Sector Z - Kill 7 White Spheres",
    "Sector Z - Kill 8 White Spheres",
    "Sector Z - Kill 9 White Spheres",
    "Sector Z - Kill 10 White Spheres",
    "Sector Z - Kill 11 White Spheres",
    "Sector Z - Kill 12 White Spheres",
    "Sector Z - Kill 13 White Spheres",
    "Sector Z - Kill 14 White Spheres",
    "Sector Z - Kill 15 White Spheres",
    "Sector Z - Kill 16 White Spheres",
    "Sector Z - Kill 17 White Spheres",
    "Sector Z - Kill 18 White Spheres",
    "Sector Z - Kill 19 White Spheres",
    "Sector Z - Kill 20 White Spheres",
    "Sector Z - Kill 21 White Spheres",
    "Sector Z - Kill 22 White Spheres",

    "Sector Z - Kill 1 Blue Fuzz",      # 823 -> 847
    "Sector Z - Kill 2 Blue Fuzzes",
    "Sector Z - Kill 3 Blue Fuzzes",
    "Sector Z - Kill 4 Blue Fuzzes",
    "Sector Z - Kill 5 Blue Fuzzes",
    "Sector Z - Kill 6 Blue Fuzzes",
    "Sector Z - Kill 7 Blue Fuzzes",
    "Sector Z - Kill 8 Blue Fuzzes",
    "Sector Z - Kill 9 Blue Fuzzes",
    "Sector Z - Kill 10 Blue Fuzzes",
    "Sector Z - Kill 11 Blue Fuzzes",
    "Sector Z - Kill 12 Blue Fuzzes",
    "Sector Z - Kill 13 Blue Fuzzes",
    "Sector Z - Kill 14 Blue Fuzzes",
    "Sector Z - Kill 15 Blue Fuzzes",
    "Sector Z - Kill 16 Blue Fuzzes",
    "Sector Z - Kill 17 Blue Fuzzes",
    "Sector Z - Kill 18 Blue Fuzzes",
    "Sector Z - Kill 19 Blue Fuzzes",
    "Sector Z - Kill 20 Blue Fuzzes",
    "Sector Z - Kill 21 Blue Fuzzes",
    "Sector Z - Kill 22 Blue Fuzzes",
    "Sector Z - Kill 23 Blue Fuzzes",
    "Sector Z - Kill 24 Blue Fuzzes",
    "Sector Z - Kill 25 Blue Fuzzes",

    "Sector Z - Kill 1 Trapper",        # 848 -> 871
    "Sector Z - Kill 2 Trappers",
    "Sector Z - Kill 3 Trappers",
    "Sector Z - Kill 4 Trappers",
    "Sector Z - Kill 5 Trappers",
    "Sector Z - Kill 6 Trappers",
    "Sector Z - Kill 7 Trappers",
    "Sector Z - Kill 8 Trappers",
    "Sector Z - Kill 9 Trappers",
    "Sector Z - Kill 10 Trappers",
    "Sector Z - Kill 11 Trappers",
    "Sector Z - Kill 12 Trappers",
    "Sector Z - Kill 13 Trappers",
    "Sector Z - Kill 14 Trappers",
    "Sector Z - Kill 15 Trappers",
    "Sector Z - Kill 16 Trappers",
    "Sector Z - Kill 17 Trappers",
    "Sector Z - Kill 18 Trappers",
    "Sector Z - Kill 19 Trappers",
    "Sector Z - Kill 20 Trappers",
    "Sector Z - Kill 21 Trappers",
    "Sector Z - Kill 22 Trappers",
    "Sector Z - Kill 23 Trappers",
    "Sector Z - Kill 24 Trappers",

    "Sector Z - Kill 1 Drone",      # 872 -> 899
    "Sector Z - Kill 2 Drones",
    "Sector Z - Kill 3 Drones",
    "Sector Z - Kill 4 Drones",
    "Sector Z - Kill 5 Drones",
    "Sector Z - Kill 6 Drones",
    "Sector Z - Kill 7 Drones",
    "Sector Z - Kill 8 Drones",
    "Sector Z - Kill 9 Drones",
    "Sector Z - Kill 10 Drones",
    "Sector Z - Kill 11 Drones",
    "Sector Z - Kill 12 Drones",
    "Sector Z - Kill 13 Drones",
    "Sector Z - Kill 14 Drones",
    "Sector Z - Kill 15 Drones",
    "Sector Z - Kill 16 Drones",
    "Sector Z - Kill 17 Drones",
    "Sector Z - Kill 18 Drones",
    "Sector Z - Kill 19 Drones",
    "Sector Z - Kill 20 Drones",
    "Sector Z - Kill 21 Drones",
    "Sector Z - Kill 22 Drones",
    "Sector Z - Kill 23 Drones",
    "Sector Z - Kill 24 Drones",
    "Sector Z - Kill 25 Drones",
    "Sector Z - Kill 26 Drones",
    "Sector Z - Kill 27 Drones",
    "Sector Z - Kill 28 Drones",
]