from BaseClasses import Location

class IjiLocation(Location):
    game="Iji"

class IjiLocData:
    id: int
    name: str
    region: str

location_sectorcomplete = {
    IjiLocData(id=1,    name="Sector 1 - Sector Complete", region="Sector 1"),
    IjiLocData(id=2,    name="Sector 2 - Sector Complete", region="Sector 2"),
    IjiLocData(id=3,    name="Sector 3 - Sector Complete", region="Sector 3"),
    IjiLocData(id=4,    name="Sector 4 - Sector Complete", region="Sector 4"),
    IjiLocData(id=5,    name="Sector 5 - Sector Complete", region="Sector 5"),
    IjiLocData(id=6,    name="Sector 6 - Sector Complete", region="Sector 6"),
    IjiLocData(id=7,    name="Sector 7 - Sector Complete", region="Sector 7"),
    IjiLocData(id=8,    name="Sector 8 - Sector Complete", region="Sector 8"),
    IjiLocData(id=9,    name="Sector 9 - Sector Complete", region="Sector 9"),
    IjiLocData(id=10,   name="Sector X - Sector Complete", region="Sector X"),
    IjiLocData(id=11,   name="Sector Z - Sector Complete", region="Sector Z"),
    IjiLocData(id=12,   name="Sector Y - Sector Complete", region="Sector Y")
}

# levelup regions change based on difficulty
location_levelup = {
    IjiLocData(id=101,  name="Level 1", region=""),
    IjiLocData(id=102,  name="Level 2", region=""),
    IjiLocData(id=103,  name="Level 3", region=""),
    IjiLocData(id=104,  name="Level 4", region=""),
    IjiLocData(id=105,  name="Level 5", region=""),
    IjiLocData(id=106,  name="Level 6", region=""),
    IjiLocData(id=107,  name="Level 7", region=""),
    IjiLocData(id=108,  name="Level 8", region=""),
    IjiLocData(id=109,  name="Level 9", region=""),
    IjiLocData(id=110,  name="Level 10", region=""),
    IjiLocData(id=111,  name="Level 11", region=""),
    IjiLocData(id=112,  name="Level 12", region=""),
    IjiLocData(id=113,  name="Level 13", region=""),
    IjiLocData(id=114,  name="Level 14", region=""),
    IjiLocData(id=115,  name="Level 15", region=""),
    IjiLocData(id=116,  name="Level 16", region=""),
    IjiLocData(id=117,  name="Level 17", region=""),
    IjiLocData(id=118,  name="Level 18", region=""),
    IjiLocData(id=119,  name="Level 19", region=""),
    IjiLocData(id=120,  name="Level 20", region=""),
    IjiLocData(id=121,  name="Level 21", region=""),
    IjiLocData(id=122,  name="Level 22", region=""),
    IjiLocData(id=123,  name="Level 23", region=""),
    IjiLocData(id=124,  name="Level 24", region=""),
    IjiLocData(id=125,  name="Level 25", region=""),
    IjiLocData(id=126,  name="Level 26", region=""),
    IjiLocData(id=127,  name="Level 27", region=""),
    IjiLocData(id=128,  name="Level 28", region=""),
    IjiLocData(id=129,  name="Level 29", region=""),
    IjiLocData(id=130,  name="Level 30", region=""),
    IjiLocData(id=131,  name="Level 31", region=""),
    IjiLocData(id=132,  name="Level 32", region=""),
    IjiLocData(id=133,  name="Level 33", region=""),
    IjiLocData(id=134,  name="Level 34", region=""),
    IjiLocData(id=135,  name="Level 35", region=""),
    IjiLocData(id=136,  name="Level 36", region=""),
    IjiLocData(id=137,  name="Level 37", region=""),
    IjiLocData(id=138,  name="Level 38", region=""),
    IjiLocData(id=139,  name="Level 39", region=""),
    IjiLocData(id=140,  name="Level 40", region=""),
    IjiLocData(id=141,  name="Level 41", region=""),
    IjiLocData(id=142,  name="Level 42", region=""),
    IjiLocData(id=143,  name="Level 43", region=""),
    IjiLocData(id=144,  name="Level 44", region=""),
    IjiLocData(id=145,  name="Level 45", region=""),
    IjiLocData(id=146,  name="Level 46", region=""),
    IjiLocData(id=147,  name="Level 47", region=""),
    IjiLocData(id=148,  name="Level 48", region=""),
    IjiLocData(id=149,  name="Level 49", region=""),
    IjiLocData(id=150,  name="Level 50", region=""),
}

location_poster = {
    IjiLocData(id=201,  name="Sector 1 - Poster", region="Sector 1 Poster"),
    IjiLocData(id=202,  name="Sector 2 - Poster", region="Sector 2 Poster"),
    IjiLocData(id=203,  name="Sector 3 - Poster", region="Sector 3 Poster"),
    IjiLocData(id=204,  name="Sector 4 - Poster", region="Sector 4 Poster"),
    IjiLocData(id=205,  name="Sector 5 - Poster", region="Sector 5 Poster"),
    IjiLocData(id=206,  name="Sector 6 - Poster", region="Sector 6 Poster"),
    IjiLocData(id=207,  name="Sector 7 - Poster", region="Sector 7 Poster"),
    IjiLocData(id=208,  name="Sector 8 - Poster", region="Sector 8 Poster"),
    IjiLocData(id=209,  name="Sector 9 - Poster", region="Sector 9 Poster"),
    IjiLocData(id=210,  name="Sector X - Poster", region="Sector X Poster"),
    IjiLocData(id=211,  name="Sector Z - Epic Poster", region="Sector Z"),
    IjiLocData(id=212,  name="Sector Y - Poster of Doom", region="Sector Y")
}

location_ribbon = {
    IjiLocData(id=221,  name="Sector 1 - Ribbon", region="Sector 1"),
    IjiLocData(id=222,  name="Sector 2 - Ribbon", region="Sector 2"),
    IjiLocData(id=223,  name="Sector 3 - Ribbon", region="Sector 3"),
    IjiLocData(id=224,  name="Sector 4 - Ribbon", region="Sector 4"),
    IjiLocData(id=225,  name="Sector 5 - Ribbon", region="Sector 5"),
    IjiLocData(id=226,  name="Sector 6 - Ribbon", region="Sector 6"),
    IjiLocData(id=227,  name="Sector 7 - Ribbon", region="Sector 7"),
    IjiLocData(id=228,  name="Sector 8 - Ribbon", region="Sector 8"),
    IjiLocData(id=229,  name="Sector 9 - Ribbon", region="Sector 9"),
    IjiLocData(id=230,  name="Sector X - Ribbon", region="Sector X")
}

location_supercharge = {
    IjiLocData(id=231,  name="Sector 1 - Supercharge", region="Sector 1 Restricted Area"),
    IjiLocData(id=232,  name="Sector 2 - Supercharge", region="Sector 2 Storage Transport Top"),
    IjiLocData(id=233,  name="Sector 3 - Supercharge", region="Sector 3"),
    IjiLocData(id=234,  name="Sector 4 - Supercharge", region="Sector 4 Top of Main Storage"),
    IjiLocData(id=235,  name="Sector 5 - Supercharge", region="Sector 5"),
    IjiLocData(id=236,  name="Sector 6 - Supercharge", region="Sector 6"),
    IjiLocData(id=237,  name="Sector 7 - Supercharge", region="Sector 7"),
    IjiLocData(id=238,  name="Sector 8 - Supercharge", region="Sector 8 Staff Storage Return Trip"),
    IjiLocData(id=239,  name="Sector 9 - Supercharge", region="Sector 9 Deep Sector"),
    IjiLocData(id=240,  name="Sector X - Supercharge", region="Sector X")
}

location_uniquebasicweapons = {
    IjiLocData(id=241,  name="Obtain Machine Gun", region="Global"),
    IjiLocData(id=242,  name="Obtain Rocket Launcher", region="Global"),
    IjiLocData(id=243,  name="Obtain MPFB Devastator", region="Global"),
    IjiLocData(id=244,  name="Obtain Resonance Detonator", region="Global"),
    IjiLocData(id=245,  name="Obtain Pulse Cannon", region="Global"),
    IjiLocData(id=246,  name="Obtain Shocksplinter", region="Global"),
    IjiLocData(id=247,  name="Obtain Cyclic Fusion Ignition System", region="Global")
}

location_uniquespecialweapons = {
    IjiLocData(id=248,  name="Obtain Banana Gun", region="Sector 9 Poster"),
    IjiLocData(id=249,  name="Obtain Massacre", region="Sector X"),
    IjiLocData(id=250,  name="Obtain Null Driver", region="Sector Z Inner Prey")
}

location_combinedweapons = {
    IjiLocData(id=251,  name="Obtain Buster Gun", region="Global"),
    IjiLocData(id=252,  name="Obtain Splintergun", region="Global"),
    IjiLocData(id=253,  name="Obtain Spread Rockets", region="Global"),
    IjiLocData(id=254,  name="Obtain Nuke", region="Global"),
    IjiLocData(id=255,  name="Obtain Resonance Reflector", region="Global"),
    IjiLocData(id=256,  name="Obtain Hyper Pulse Cannon", region="Global"),
    IjiLocData(id=257,  name="Obtain Plasma Cannon", region="Global"),
    IjiLocData(id=258,  name="Obtain Velocithor V2-10", region="Global")
}

location_upgrades = {
    IjiLocData(id=261,  name="Sector 2 - Jump Upgrade", region="Sector 2"),
    IjiLocData(id=262,  name="Sector 3 - Armor Upgrade", region="Sector 3"),
    IjiLocData(id=263,  name="Sector 5 - Jump Upgrade", region="Sector 5"),
    IjiLocData(id=264,  name="Sector 7 - Armor Upgrade", region="Sector 7"),
    IjiLocData(id=265,  name="Sector 8 - Armor Upgrade", region="Sector 8"),
    IjiLocData(id=266,  name="Sector 9 - Armor Upgrade", region="Sector 9"),
    IjiLocData(id=267,  name="Sector X - Armor Upgrade", region="Sector X")
}

location_sectorweapons = {
    IjiLocData(id=311,  name="Sector 1 - Machine Gun", region="Sector 1"),
    IjiLocData(id=321,  name="Sector 2 - Machine Gun", region="Sector 2"),
    IjiLocData(id=322,  name="Sector 2 - Rocket Launcher", region="Sector 2 Storage Transport Top"),
    IjiLocData(id=324,  name="Sector 2 - Resonance Detonator", region="Sector 2"),
    IjiLocData(id=331,  name="Sector 3 - Machine Gun", region="Sector 3"),
    IjiLocData(id=332,  name="Sector 3 - Rocket Launcher", region="Sector 3"),
    IjiLocData(id=334,  name="Sector 3 - Resonance Detonator", region="Sector 3"),
    IjiLocData(id=335,  name="Sector 3 - Pulse Cannon", region="Sector 3"),
    IjiLocData(id=341,  name="Sector 4 - Machine Gun", region="Sector 4"),
    IjiLocData(id=342,  name="Sector 4 - Rocket Launcher", region="Sector 4"),
    IjiLocData(id=343,  name="Sector 4 - MPFB Devastator", region="Sector 4 Top of Main Storage"),
    IjiLocData(id=344,  name="Sector 4 - Resonance Detonator", region="Sector 4"),
    IjiLocData(id=345,  name="Sector 4 - Pulse Cannon", region="Sector 4"),
    IjiLocData(id=351,  name="Sector 5 - Machine Gun",region="Sector 5"),
    IjiLocData(id=352,  name="Sector 5 - Rocket Launcher",region="Sector 5"),
    IjiLocData(id=353,  name="Sector 5 - MPFB Devastator", region="Sector 5"),
    IjiLocData(id=354,  name="Sector 5 - Resonance Detonator", region="Sector 5"),
    IjiLocData(id=355,  name="Sector 5 - Pulse Cannon", region="Sector 5"),
    IjiLocData(id=356,  name="Sector 5 - Shocksplinter", region="Sector 5"),
    IjiLocData(id=361,  name="Sector 6 - Machine Gun",region="Sector 6"),
    IjiLocData(id=362,  name="Sector 6 - Rocket Launcher", region="Sector 6"),
    IjiLocData(id=363,  name="Sector 6 - MPFB Devastator", region="Sector 6"),
    IjiLocData(id=364,  name="Sector 6 - Resonance Detonator", region="Sector 6"),
    IjiLocData(id=365,  name="Sector 6 - Pulse Cannon", region="Sector 6"),
    IjiLocData(id=366,  name="Sector 6 - Shocksplinter", region="Sector 6"),
    IjiLocData(id=367,  name="Sector 6 - Cyclic Fusion Ignition System", region="Sector 6"),
    IjiLocData(id=371,  name="Sector 7 - Machine Gun", region="Sector 7"),
    IjiLocData(id=372,  name="Sector 7 - Rocket Launcher", region="Sector 7"),
    IjiLocData(id=373,  name="Sector 7 - MPFB Devastator", region="Sector 7"),
    IjiLocData(id=374,  name="Sector 7 - Resonance Detonator", region="Sector 7"),
    IjiLocData(id=375,  name="Sector 7 - Pulse Cannon", region="Sector 7"),
    IjiLocData(id=376,  name="Sector 7 - Shocksplinter", region="Sector 7"),
    IjiLocData(id=377,  name="Sector 7 - Cyclic Fusion Ignition System", region="Sector 7 Heavy Weapon Armory"),
    IjiLocData(id=381,  name="Sector 8 - Machine Gun", region="Sector 8"),
    IjiLocData(id=382,  name="Sector 8 - Rocket Launcher", region="Sector 8"),
    IjiLocData(id=383,  name="Sector 8 - MPFB Devastator", region="Sector 8"),
    IjiLocData(id=384,  name="Sector 8 - Resonance Detonator",region="Sector 8"),
    IjiLocData(id=385,  name="Sector 8 - Pulse Cannon", region="Sector 8"),
    IjiLocData(id=386,  name="Sector 8 - Shocksplinter",region="Sector 8"),
    IjiLocData(id=387,  name="Sector 8 - Cyclic Fusion Ignition System", region="Sector 8"),
    IjiLocData(id=391,  name="Sector 9 - Machine Gun", region="Sector 9"),
    IjiLocData(id=392,  name="Sector 9 - Rocket Launcher", region="Sector 9"),
    IjiLocData(id=393,  name="Sector 9 - MPFB Devastator", region="Sector 9"),
    IjiLocData(id=394,  name="Sector 9 - Resonance Detonator", region="Sector 9"),
    IjiLocData(id=395,  name="Sector 9 - Pulse Cannon", region="Sector 9"),
    IjiLocData(id=396,  name="Sector 9 - Shocksplinter", region="Sector 9"),
    IjiLocData(id=397,  name="Sector 9 - Cyclic Fusion Ignition System", region="Sector 9"),
    IjiLocData(id=301,  name="Sector X - Machine Gun", region="Sector X"),
    IjiLocData(id=302,  name="Sector X - Rocket Launcher", region="Sector X"),
    IjiLocData(id=303,  name="Sector X - MPFB Devastator", region="Sector X"),
    IjiLocData(id=304,  name="Sector X - Resonance Detonator", region="Sector X"),
    IjiLocData(id=305,  name="Sector X - Pulse Cannon", region="Sector X"),
    IjiLocData(id=306,  name="Sector X - Shocksplinter", region="Sector X"),
    IjiLocData(id=307,  name="Sector X - Cyclic Fusion Ignition System", region="Sector X"),
    IjiLocData(id=308,  name="Sector X - Resonance Reflector", region="Sector X")
}

location_allweapons = {
    IjiLocData(id=3111, name="Sector 1 - Machine Gun", region="Sector 1"),
    IjiLocData(id=3211, name="Sector 2 - Machine Gun", region="Sector 2"),
    IjiLocData(id=3221, name="Sector 2 - Rocket Launcher", region="Sector 2 Storage Transport Top"),
    IjiLocData(id=3241, name="Sector 2 - Resonance Detonator", region="Sector 2"),
    IjiLocData(id=3311, name="Sector 3 - Machine Gun 1", region="Sector 3"),
    IjiLocData(id=3312, name="Sector 3 - Machine Gun 2", region="Sector 3"),
    IjiLocData(id=3313, name="Sector 3 - Machine Gun 3", region="Sector 3"),
    IjiLocData(id=3321, name="Sector 3 - Rocket Launcher 1", region="Sector 3"),
    IjiLocData(id=3322, name="Sector 3 - Rocket Launcher 2", region="Sector 3"),
    IjiLocData(id=3341, name="Sector 3 - Resonance Detonator",region="Sector 3"),
    IjiLocData(id=3351, name="Sector 3 - Pulse Cannon", region="Sector 3"),
    IjiLocData(id=3411, name="Sector 4 - Machine Gun", region="Sector 4"),
    IjiLocData(id=3421, name="Sector 4 - Rocket Launcher 1", region="Sector 4"),
    IjiLocData(id=3422, name="Sector 4 - Rocket Launcher 2", region="Sector 4"),
    IjiLocData(id=3431, name="Sector 4 - MPFB Devastator", region="Sector 4 Top of Main Storage"),
    IjiLocData(id=3441, name="Sector 4 - Resonance Detonator", region="Sector 4"),
    IjiLocData(id=3451, name="Sector 4 - Pulse Cannon", region="Sector 4"),
    IjiLocData(id=3511, name="Sector 5 - Machine Gun 1", region="Sector 5"),
    IjiLocData(id=3512, name="Sector 5 - Machine Gun 2", region="Sector 5"),
    IjiLocData(id=3521, name="Sector 5 - Rocket Launcher 1", region="Sector 5"),
    IjiLocData(id=3522, name="Sector 5 - Rocket Launcher 2", region="Sector 5"),
    IjiLocData(id=3531, name="Sector 5 - MPFB Devastator", region="Sector 5"),
    IjiLocData(id=3541, name="Sector 5 - Resonance Detonator", region="Sector 5"),
    IjiLocData(id=3551, name="Sector 5 - Pulse Cannon 1", region="Sector 5"),
    IjiLocData(id=3552, name="Sector 5 - Pulse Cannon 2", region="Sector 5"),
    IjiLocData(id=3553, name="Sector 5 - Pulse Cannon 3", region="Sector 5"),
    IjiLocData(id=3561, name="Sector 5 - Shocksplinter", region="Sector 5"),
    IjiLocData(id=3611, name="Sector 6 - Machine Gun 1", region="Sector 6"),
    IjiLocData(id=3612, name="Sector 6 - Machine Gun 2", region="Sector 6"),
    IjiLocData(id=3621, name="Sector 6 - Rocket Launcher 1", region="Sector 6"),
    IjiLocData(id=3622, name="Sector 6 - Rocket Launcher 2", region="Sector 6"),
    IjiLocData(id=3631, name="Sector 6 - MPFB Devastator 1", region="Sector 6"),
    IjiLocData(id=3632, name="Sector 6 - MPFB Devastator 2", region="Sector 6"),
    IjiLocData(id=3641, name="Sector 6 - Resonance Detonator", region="Sector 6"),
    IjiLocData(id=3651, name="Sector 6 - Pulse Cannon 1", region="Sector 6"),
    IjiLocData(id=3652, name="Sector 6 - Pulse Cannon 2", region="Sector 6"),
    IjiLocData(id=3661, name="Sector 6 - Shocksplinter 1", region="Sector 6"),
    IjiLocData(id=3662, name="Sector 6 - Shocksplinter 2", region="Sector 6"),
    IjiLocData(id=3663, name="Sector 6 - Shocksplinter 3", region="Sector 6"),
    IjiLocData(id=3671, name="Sector 6 - Cyclic Fusion Ignition System", region="Sector 6"),
    IjiLocData(id=3711, name="Sector 7 - Machine Gun", region= "Sector 7"),
    IjiLocData(id=3721, name="Sector 7 - Rocket Launcher 1", region="Sector 7"),
    IjiLocData(id=3722, name="Sector 7 - Rocket Launcher 2", region="Sector 7"),
    IjiLocData(id=3723, name="Sector 7 - Rocket Launcher 3", region="Sector 7"),
    IjiLocData(id=3731, name="Sector 7 - MPFB Devastator", region="Sector 7"),
    IjiLocData(id=3741, name="Sector 7 - Resonance Detonator 1", region="Sector 7"),
    IjiLocData(id=3742, name="Sector 7 - Resonance Detonator 2", region="Sector 7"),
    IjiLocData(id=3751, name="Sector 7 - Pulse Cannon 1", region="Sector 7"),
    IjiLocData(id=3752, name="Sector 7 - Pulse Cannon 2", region="Sector 7"),
    IjiLocData(id=3761, name="Sector 7 - Shocksplinter 1", region="Sector 7"),
    IjiLocData(id=3762, name="Sector 7 - Shocksplinter 2", region="Sector 7"),
    IjiLocData(id=3763, name="Sector 7 - Shocksplinter 3", region="Sector 7"),
    IjiLocData(id=3771, name="Sector 7 - Cyclic Fusion Ignition System", region="Sector 7 Heavy Weapon Armory"),
    IjiLocData(id=3811, name="Sector 8 - Machine Gun", region="Sector 8"),
    IjiLocData(id=3821, name="Sector 8 - Rocket Launcher 1", region="Sector 8"),
    IjiLocData(id=3822, name="Sector 8 - Rocket Launcher 2", region="Sector 8"),
    IjiLocData(id=3823, name="Sector 8 - Rocket Launcher 3", region="Sector 8"),
    IjiLocData(id=3831, name="Sector 8 - MPFB Devastator", region="Sector 8"),
    IjiLocData(id=3841, name="Sector 8 - Resonance Detonator", region="Sector 8"),
    IjiLocData(id=3851, name="Sector 8 - Pulse Cannon 1", region="Sector 8"),
    IjiLocData(id=3852, name="Sector 8 - Pulse Cannon 2", region="Sector 8"),
    IjiLocData(id=3861, name="Sector 8 - Shocksplinter 1", region="Sector 8"),
    IjiLocData(id=3862, name="Sector 8 - Shocksplinter 2", region="Sector 8"),
    IjiLocData(id=3871, name="Sector 8 - Cyclic Fusion Ignition System", region="Sector 8"),
    IjiLocData(id=3911, name="Sector 9 - Machine Gun 1", region="Sector 9"),
    IjiLocData(id=3912, name="Sector 9 - Machine Gun 2", region="Sector 9"),
    IjiLocData(id=3913, name="Sector 9 - Machine Gun 3", region="Sector 9"),
    IjiLocData(id=3914, name="Sector 9 - Machine Gun 4", region="Sector 9 Poster"),
    IjiLocData(id=3921, name="Sector 9 - Rocket Launcher 1", region="Sector 9"),
    IjiLocData(id=3922, name="Sector 9 - Rocket Launcher 2", region="Sector 9"),
    IjiLocData(id=3923, name="Sector 9 - Rocket Launcher 3", region="Sector 9"),
    IjiLocData(id=3924, name="Sector 9 - Rocket Launcher 4", region="Sector 9"),
    IjiLocData(id=3925, name="Sector 9 - Rocket Launcher 5", region="Sector 9 Poster"),
    IjiLocData(id=3931, name="Sector 9 - MPFB Devastator 1", region="Sector 9"),
    IjiLocData(id=3932, name="Sector 9 - MPFB Devastator 2", region="Sector 9"),
    IjiLocData(id=3933, name="Sector 9 - MPFB Devastator 3", region="Sector 9"),
    IjiLocData(id=3934, name="Sector 9 - MPFB Devastator 4", region="Sector 9 Poster"),
    IjiLocData(id=3941, name="Sector 9 - Resonance Detonator 1", region="Sector 9"),
    IjiLocData(id=3942, name="Sector 9 - Resonance Detonator 2", region="Sector 9"),
    IjiLocData(id=3943, name="Sector 9 - Resonance Detonator 3", region="Sector 9"),
    IjiLocData(id=3944, name="Sector 9 - Resonance Detonator 4", region="Sector 9 Poster"),
    IjiLocData(id=3951, name="Sector 9 - Pulse Cannon 1", region="Sector 9"),
    IjiLocData(id=3952, name="Sector 9 - Pulse Cannon 2", region="Sector 9"),
    IjiLocData(id=3953, name="Sector 9 - Pulse Cannon 3", region="Sector 9"),
    IjiLocData(id=3954, name="Sector 9 - Pulse Cannon 4", region="Sector 9 Poster"),
    IjiLocData(id=3961, name="Sector 9 - Shocksplinter 1", region="Sector 9"),
    IjiLocData(id=3962, name="Sector 9 - Shocksplinter 2", region="Sector 9"),
    IjiLocData(id=3963, name="Sector 9 - Shocksplinter 3", region="Sector 9"),
    IjiLocData(id=3964, name="Sector 9 - Shocksplinter 4", region="Sector 9 Poster"),
    IjiLocData(id=3971, name="Sector 9 - Cyclic Fusion Ignition System 1", region="Sector 9"),
    IjiLocData(id=3972, name="Sector 9 - Cyclic Fusion Ignition System 2", region="Sector 9"),
    IjiLocData(id=3973, name="Sector 9 - Cyclic Fusion Ignition System 3", region="Sector 9 Poster"),
    IjiLocData(id=3011, name="Sector X - Machine Gun 1", region="Sector X"),
    IjiLocData(id=3012, name="Sector X - Machine Gun 2",region="Sector X"),
    IjiLocData(id=3013, name="Sector X - Machine Gun 3", region="Sector X"),
    IjiLocData(id=3021, name="Sector X - Rocket Launcher 1", region="Sector X"),
    IjiLocData(id=3022, name="Sector X - Rocket Launcher 2", region="Sector X"),
    IjiLocData(id=3023, name="Sector X - Rocket Launcher 3", region="Sector X"),
    IjiLocData(id=3031, name="Sector X - MPFB Devastator 1", region="Sector X"),
    IjiLocData(id=3032, name="Sector X - MPFB Devastator 2", region="Sector X"),
    IjiLocData(id=3033, name="Sector X - MPFB Devastator 3", region="Sector X"),
    IjiLocData(id=3034, name="Sector X - MPFB Devastator 4", region="Sector X"),
    IjiLocData(id=3041, name="Sector X - Resonance Detonator 1", region="Sector X"),
    IjiLocData(id=3042, name="Sector X - Resonance Detonator 2", region="Sector X"),
    IjiLocData(id=3051, name="Sector X - Pulse Cannon 1", region="Sector X"),
    IjiLocData(id=3052, name="Sector X - Pulse Cannon 2", region="Sector X"),
    IjiLocData(id=3053, name="Sector X - Pulse Cannon 3", region="Sector X"),
    IjiLocData(id=3054, name="Sector X - Pulse Cannon 4", region="Sector X"),
    IjiLocData(id=3061, name="Sector X - Shocksplinter 1", region="Sector X"),
    IjiLocData(id=3062, name="Sector X - Shocksplinter 2", region="Sector X"),
    IjiLocData(id=3063, name="Sector X - Shocksplinter 3", region="Sector X"),
    IjiLocData(id=3071, name="Sector X - Cyclic Fusion Ignition System 1", region="Sector X"),
    IjiLocData(id=3072, name="Sector X - Cyclic Fusion Ignition System 2", region="Sector X"),
    IjiLocData(id=3073, name="Sector X - Cyclic Fusion Ignition System 3", region="Sector X"),
    IjiLocData(id=3074, name="Sector X - Cyclic Fusion Ignition System 4", region="Sector X"),
    IjiLocData(id=3081, name="Sector X - Resonance Reflector", region="Sector X")
}

location_logbooks = {
    IjiLocData(id=1101, name="Sector 1 - Logbook 1", region="Sector 1"),
    IjiLocData(id=1102, name="Sector 1 - Logbook 2", region="Sector 1"),
    IjiLocData(id=1103, name="Sector 1 - Logbook 3", region="Sector 1"),
    IjiLocData(id=1104, name="Sector 1 - Logbook 4", region="Sector 1"),
    IjiLocData(id=1105, name="Sector 1 - Logbook 5", region="Sector 1"),
    IjiLocData(id=1106, name="Sector 1 - Logbook 6", region="Sector 1"),
    IjiLocData(id=1107, name="Sector 1 - Logbook 7", region="Sector 1"),
    IjiLocData(id=1108, name="Sector 1 - Logbook 8", region="Sector 1"),
    IjiLocData(id=1109, name="Sector 1 - Logbook 9", region="Sector 1"),
    IjiLocData(id=1110, name="Sector 1 - Logbook 10", region="Sector 1"),
    IjiLocData(id=1111, name="Sector 1 - Logbook 11", region="Sector 1 Poster"),
    IjiLocData(id=1112, name="Sector 1 - Logbook 12", region="Sector 1 Poster"),
    IjiLocData(id=1113, name="Sector 1 - Logbook 13", region="Sector 1 Poster"),
    IjiLocData(id=1114, name="Sector 1 - Logbook 14", region="Sector 1 Poster"),
    IjiLocData(id=1115, name="Sector 1 - Logbook 15", region="Sector 1 Restricted Area"),
    IjiLocData(id=1201, name="Sector 2 - Logbook 1", region="Sector 2"),
    IjiLocData(id=1202, name="Sector 2 - Logbook 2", region="Sector 2"),
    IjiLocData(id=1203, name="Sector 2 - Logbook 3", region="Sector 2"),
    IjiLocData(id=1204, name="Sector 2 - Logbook 4", region="Sector 2"),
    IjiLocData(id=1205, name="Sector 2 - Logbook 5", region="Sector 2"),
    IjiLocData(id=1206, name="Sector 2 - Logbook 6", region="Sector 2"),
    IjiLocData(id=1207, name="Sector 2 - Logbook 7", region="Sector 2"),
    IjiLocData(id=1208, name="Sector 2 - Logbook 8", region="Sector 2"),
    IjiLocData(id=1209, name="Sector 2 - Logbook 9", region="Sector 2"),
    IjiLocData(id=1210, name="Sector 2 - Logbook 10", region="Sector 2"),
    IjiLocData(id=1211, name="Sector 2 - Logbook 11", region="Sector 2"),
    IjiLocData(id=1212, name="Sector 2 - Logbook 12", region="Sector 2"),
    IjiLocData(id=1213, name="Sector 2 - Logbook 13", region="Sector 2"),
    IjiLocData(id=1214, name="Sector 2 - Logbook 14", region="Sector 2"),
    IjiLocData(id=1215, name="Sector 2 - Logbook 15", region="Sector 2 Poster"),
    IjiLocData(id=1216, name="Sector 2 - Logbook 16", region="Sector 2 Poster"),
    IjiLocData(id=1301, name="Sector 3 - Logbook 1", region="Sector 3"),
    IjiLocData(id=1302, name="Sector 3 - Logbook 2", region="Sector 3"),
    IjiLocData(id=1303, name="Sector 3 - Logbook 3", region="Sector 3"),
    IjiLocData(id=1304, name="Sector 3 - Logbook 4", region="Sector 3"),
    IjiLocData(id=1305, name="Sector 3 - Logbook 5", region="Sector 3"),
    IjiLocData(id=1306, name="Sector 3 - Logbook 6", region="Sector 3"),
    IjiLocData(id=1307, name="Sector 3 - Logbook 7", region="Sector 3"),
    IjiLocData(id=1308, name="Sector 3 - Logbook 8", region="Sector 3"),
    IjiLocData(id=1309, name="Sector 3 - Logbook 9", region="Sector 3"),
    IjiLocData(id=1310, name="Sector 3 - Logbook 10", region="Sector 3"),
    IjiLocData(id=1311, name="Sector 3 - Logbook 11", region="Sector 3"),
    IjiLocData(id=1312, name="Sector 3 - Logbook 12", region="Sector 3"),
    IjiLocData(id=1313, name="Sector 3 - Logbook 13", region="Sector 3"),
    IjiLocData(id=1314, name="Sector 3 - Logbook 14", region="Sector 3"),
    IjiLocData(id=1315, name="Sector 3 - Logbook 15", region="Sector 3"),
    IjiLocData(id=1316, name="Sector 3 - Logbook 16", region="Sector 3 Restricted Area"),
    IjiLocData(id=1317, name="Sector 3 - Logbook 17", region="Sector 3 Restricted Area"),
    IjiLocData(id=1318, name="Sector 3 - Logbook 18", region="Sector 3 Poster"),
    IjiLocData(id=1401, name="Sector 4 - Logbook 1", region="Sector 4"),
    IjiLocData(id=1402, name="Sector 4 - Logbook 2", region="Sector 4"),
    IjiLocData(id=1403, name="Sector 4 - Logbook 3", region="Sector 4"),
    IjiLocData(id=1404, name="Sector 4 - Logbook 4", region="Sector 4"),
    IjiLocData(id=1405, name="Sector 4 - Logbook 5", region="Sector 4"),
    IjiLocData(id=1406, name="Sector 4 - Logbook 6", region="Sector 4"),
    IjiLocData(id=1407, name="Sector 4 - Logbook 7", region="Sector 4"),
    IjiLocData(id=1408, name="Sector 4 - Logbook 8", region="Sector 4"),
    IjiLocData(id=1409, name="Sector 4 - Logbook 9", region="Sector 4"),
    IjiLocData(id=1410, name="Sector 4 - Logbook 10", region="Sector 4 Surveillance Control"),
    IjiLocData(id=1411, name="Sector 4 - Logbook 11", region="Sector 4 Top of Main Storage"),
    IjiLocData(id=1412, name="Sector 4 - Logbook 12", region="Sector 4"),
    IjiLocData(id=1413, name="Sector 4 - Logbook 13", region="Sector 4 Poster"),
    IjiLocData(id=1501, name="Sector 5 - Logbook 1", region="Sector 5"),
    IjiLocData(id=1502, name="Sector 5 - Logbook 2", region="Sector 5"),
    IjiLocData(id=1503, name="Sector 5 - Logbook 3", region="Sector 5"),
    IjiLocData(id=1504, name="Sector 5 - Logbook 4", region="Sector 5"),
    IjiLocData(id=1505, name="Sector 5 - Logbook 5", region="Sector 5"),
    IjiLocData(id=1506, name="Sector 5 - Logbook 6", region="Sector 5"),
    IjiLocData(id=1507, name="Sector 5 - Logbook 7", region="Sector 5"),
    IjiLocData(id=1508, name="Sector 5 - Logbook 8", region="Sector 5"),
    IjiLocData(id=1509, name="Sector 5 - Logbook 9", region="Sector 5"),
    IjiLocData(id=1510, name="Sector 5 - Logbook 10", region="Sector 5"),
    IjiLocData(id=1601, name="Sector 6 - Logbook 1", region="Sector 6"),
    IjiLocData(id=1602, name="Sector 6 - Logbook 2", region="Sector 6"),
    IjiLocData(id=1603, name="Sector 6 - Logbook 3", region="Sector 6"),
    IjiLocData(id=1604, name="Sector 6 - Logbook 4", region="Sector 6"),
    IjiLocData(id=1605, name="Sector 6 - Logbook 5", region="Sector 6"),
    IjiLocData(id=1606, name="Sector 6 - Logbook 6", region="Sector 6"),
    IjiLocData(id=1607, name="Sector 6 - Logbook 7", region="Sector 6"),
    IjiLocData(id=1608, name="Sector 6 - Logbook 8", region="Sector 6"),
    IjiLocData(id=1609, name="Sector 6 - Logbook 9", region="Sector 6"),
    IjiLocData(id=1610, name="Sector 6 - Logbook 10", region="Sector 6"),
    IjiLocData(id=1611, name="Sector 6 - Logbook 11", region="Sector 6 Poster"),
    IjiLocData(id=1701, name="Sector 7 - Logbook 1", region="Sector 7"),
    IjiLocData(id=1702, name="Sector 7 - Logbook 2", region="Sector 7"),
    IjiLocData(id=1703, name="Sector 7 - Logbook 3", region="Sector 7"),
    IjiLocData(id=1704, name="Sector 7 - Logbook 4", region="Sector 7"),
    IjiLocData(id=1705, name="Sector 7 - Logbook 5", region="Sector 7"),
    IjiLocData(id=1706, name="Sector 7 - Logbook 6", region="Sector 7"),
    IjiLocData(id=1707, name="Sector 7 - Logbook 7", region="Sector 7"),
    IjiLocData(id=1708, name="Sector 7 - Logbook 8", region="Sector 7"),
    IjiLocData(id=1709, name="Sector 7 - Logbook 9", region="Sector 7"),
    IjiLocData(id=1710, name="Sector 7 - Logbook 10", region="Sector 7"),
    IjiLocData(id=1711, name="Sector 7 - Logbook 11", region="Sector 7"),
    IjiLocData(id=1712, name="Sector 7 - Logbook 12", region="Sector 7"),
    IjiLocData(id=1713, name="Sector 7 - Logbook 13", region="Sector 7"),
    IjiLocData(id=1714, name="Sector 7 - Logbook 14", region="Sector 7 "),
    IjiLocData(id=1715, name="Sector 7 - Logbook 15", region="Sector 7 Heavy Weapon Armory"),
    IjiLocData(id=1716, name="Sector 7 - Logbook 16", region="Sector 7 Hyper Turret Logbooks"),
    IjiLocData(id=1717, name="Sector 7 - Logbook 17", region="Sector 7 Hyper Turret Logbooks"),
    IjiLocData(id=1718, name="Sector 7 - Logbook 18", region="Sector 7 Poster"),
    IjiLocData(id=1719, name="Sector 7 - Logbook 19", region="Sector 7 Poster"),
    IjiLocData(id=1720, name="Sector 7 - Logbook 20", region="Sector 7 Crackers' Hideout"),
    IjiLocData(id=1721, name="Sector 7 - Logbook 21", region="Sector 7 Crackers' Hideout"),
    IjiLocData(id=1722, name="Sector 7 - Logbook 22", region="Sector 7 Crackers' Hideout"),
    IjiLocData(id=1801, name="Sector 8 - Logbook 1", region="Sector 8"),
    IjiLocData(id=1802, name="Sector 8 - Logbook 2", region="Sector 8"),
    IjiLocData(id=1803, name="Sector 8 - Logbook 3", region="Sector 8"),
    IjiLocData(id=1804, name="Sector 8 - Logbook 4", region="Sector 8"),
    IjiLocData(id=1805, name="Sector 8 - Logbook 5", region="Sector 8"),
    IjiLocData(id=1806, name="Sector 8 - Logbook 6", region="Sector 8"),
    IjiLocData(id=1807, name="Sector 8 - Logbook 7", region="Sector 8"),
    IjiLocData(id=1808, name="Sector 8 - Logbook 8", region="Sector 8"),
    IjiLocData(id=1809, name="Sector 8 - Logbook 9", region="Sector 8"),
    IjiLocData(id=1810, name="Sector 8 - Logbook 10", region="Sector 8"),
    IjiLocData(id=1811, name="Sector 8 - Logbook 11", region="Sector 8"),
    IjiLocData(id=1812, name="Sector 8 - Logbook 12", region="Sector 8"),
    IjiLocData(id=1813, name="Sector 8 - Logbook 13", region="Sector 8 Staff Storage Return Trip"),
    IjiLocData(id=1814, name="Sector 8 - Logbook 14", region="Sector 8 Poster"),
    IjiLocData(id=1815, name="Sector 8 - Logbook 15", region="Sector 8"),
    IjiLocData(id=1901, name="Sector 9 - Logbook 1", region="Sector 9"),
    IjiLocData(id=1902, name="Sector 9 - Logbook 2", region="Sector 9"),
    IjiLocData(id=1903, name="Sector 9 - Logbook 3", region="Sector 9"),
    IjiLocData(id=1904, name="Sector 9 - Logbook 4", region="Sector 9"),
    IjiLocData(id=1905, name="Sector 9 - Logbook 5", region="Sector 9"),
    IjiLocData(id=1906, name="Sector 9 - Logbook 6", region="Sector 9"),
    IjiLocData(id=1907, name="Sector 9 - Logbook 7", region="Sector 9"),
    IjiLocData(id=1908, name="Sector 9 - Logbook 8", region="Sector 9"),
    IjiLocData(id=1909, name="Sector 9 - Logbook 9", region="Sector 9"),
    IjiLocData(id=1910, name="Sector 9 - Logbook 10", region="Sector 9"),
    IjiLocData(id=1911, name="Sector 9 - Logbook 11", region="Sector 9"),
    IjiLocData(id=1912, name="Sector 9 - Logbook 12", region="Sector 9"),
    IjiLocData(id=1913, name="Sector 9 - Logbook 13", region="Sector 9"),
    IjiLocData(id=1914, name="Sector 9 - Logbook 14", region="Sector 9 Poster"),
    IjiLocData(id=1915, name="Sector 9 - Logbook 15", region="Sector 9"),
    IjiLocData(id=1916, name="Sector 9 - Logbook 16", region="Sector 9 Deep Sector"),
    IjiLocData(id=1917, name="Sector 9 - Logbook 17", region="Sector 9 Deep Sector"),
    IjiLocData(id=1918, name="Sector 9 - Logbook 18", region="Sector 9 Deep Sector"),
    IjiLocData(id=1919, name="Sector 9 - Logbook 19", region="Sector 9 Deep Sector"),
    IjiLocData(id=1001, name="Sector X - Logbook 1", region="Sector X"),
    IjiLocData(id=1002, name="Sector X - Logbook 2", region="Sector X"),
    IjiLocData(id=1003, name="Sector X - Logbook 3", region="Sector X"),
    IjiLocData(id=1004, name="Sector X - Logbook 4", region="Sector X"),
    IjiLocData(id=1005, name="Sector X - Logbook 5", region="Sector X"),
    IjiLocData(id=1006, name="Sector X - Logbook 6", region="Sector X"),
    IjiLocData(id=1007, name="Sector X - Logbook 7", region="Sector X"),
    IjiLocData(id=1008, name="Sector X - Logbook 8", region="Sector X"),
    IjiLocData(id=1009, name="Sector X - Logbook 9", region="Sector X"),
    IjiLocData(id=1010, name="Sector X - Logbook 10", region="Sector X"),
    IjiLocData(id=1011, name="Sector X - Logbook 11", region="Sector X"),
    IjiLocData(id=1012, name="Sector X - Logbook 12", region="Sector X"),
    IjiLocData(id=1013, name="Sector X - Logbook 13", region="Sector X"),
    IjiLocData(id=1014, name="Sector X - Logbook 14", region="Sector X"),
    IjiLocData(id=1015, name="Sector X - Logbook 15", region="Sector X"),
    IjiLocData(id=1016, name="Sector X - Logbook 16", region="Sector X"),
    IjiLocData(id=1017, name="Sector X - Logbook 17", region="Sector X"),
    IjiLocData(id=1018, name="Sector X - Logbook 18", region="Sector X"),
    IjiLocData(id=1019, name="Sector X - Logbook 19", region="Sector X"),
    IjiLocData(id=1020, name="Sector X - Logbook 20", region="Sector X"),
    IjiLocData(id=1021, name="Sector X - Logbook 21", region="Sector X"),
    IjiLocData(id=1022, name="Sector X - Logbook 22", region="Sector X Ventilation Shaft"),
    IjiLocData(id=1023, name="Sector X - Logbook 23", region="Sector X Ultimate Charge Terminal"),
    IjiLocData(id=1024, name="Sector X - Logbook 24", region="Sector X Ultimate Charge Terminal"),
    IjiLocData(id=1025, name="Sector X - Logbook 25", region="Sector X Ultimate Charge Terminal"),
    IjiLocData(id=1116, name="Sector Z - Logbook 1", region="Sector Z"),
    IjiLocData(id=1117, name="Sector Z - Logbook 2", region="Sector Z"),
    IjiLocData(id=1118, name="Sector Y - Logbook 1", region="Sector Y"),
    IjiLocData(id=1119, name="Sector Y - Logbook 2", region="Sector Y"),
    IjiLocData(id=1120, name="Sector Y - Logbook 3", region="Sector Y"),
    IjiLocData(id=1121, name="Sector Y - Logbook 4", region="Sector Y"),
    IjiLocData(id=1122, name="Sector Y - Logbook 5", region="Sector Y"),
    IjiLocData(id=1123, name="Sector Y - Logbook 6", region="Sector Y"),
    IjiLocData(id=1124, name="Sector Y - Logbook 7", region="Sector Y"),
    IjiLocData(id=1125, name="Sector Y - Logbook 8", region="Sector Y"),
    IjiLocData(id=1126, name="Sector Y - Logbook 9", region="Sector Y"),
    IjiLocData(id=1127, name="Sector Y - Logbook 10", region="Sector Y"),
    IjiLocData(id=1128, name="Sector Y - Logbook 11", region="Sector Y"),
    IjiLocData(id=1129, name="Sector Y - Logbook 12", region="Sector Y"),
    IjiLocData(id=1130, name="Sector Y - Logbook 13", region="Sector Y"),
    IjiLocData(id=1131, name="Sector Y - Logbook 14", region="Sector Y"),
    IjiLocData(id=1132, name="Sector Y - Logbook 15", region="Sector Y")
}

# location_doorsanity: [int, IjiLocData] = {2001->2999}

# location_killsanity: [int, IjiLocData] = {10001->19999}

#location_pickupsanity: [int,IjiLocData] = {20001->29999}