
from typing import Callable, Dict, List, TYPE_CHECKING, NamedTuple
from BaseClasses import MultiWorld, Region, Entrance, CollectionState
from worlds.generic.Rules import CollectionRule
from worlds.iji.Rules import can_access_sector, can_reach_nulldriver, can_reach_poster_nine, can_reach_sector_z, can_rocket_boost, has_stats, has_multiple_stats, has_weapon_stats
from .Locations import IjiLocation, location_table
from .Data import RegNames


if TYPE_CHECKING:
    from . import IjiWorld

def create_regions(world: "IjiWorld"):
    existing_regions: List[str] = []
    create_region_and_exits(world, "Menu", existing_regions)



def create_region_and_exits(world: "IjiWorld", name: str, existing_regions: List[str]) -> Region:
    region = Region(name, world.player, world.multiworld)

    
    region.add_locations({
        location_name: location_data.code for location_name, location_data in location_table.items()
        if location_data.region==region.name and location_data.valid(world)
    }, IjiLocation)

    return region

def create_exits(world: "IjiWorld", state: CollectionState, region_name: str, existing_regions: List[str]):
    pass

class IjiRegionExit(NamedTuple):
    valid: Callable[["IjiWorld"], bool] = lambda world: True
    logic: Callable[["IjiWorld", CollectionState], bool] = lambda world, state: True

region_exit_table: Dict[str, Dict[str, IjiRegionExit]] = {
    RegNames.menu: {
        RegNames.glo: IjiRegionExit(),
        RegNames.sec_1_1: IjiRegionExit()},
    RegNames.glo: {},

    "Sector 1 Start": {},
    "Sector 1 Poster": {},
    "Sector 1 Used Materials Access": {},
    "Sector 1 Supercharge": {},
    "Sector 1 Guard Post": {},
    "Sector 1 Emergency Armory": {},
    "Sector 1 Medical Surplus": {},

    "Sector Z Start": {},
    "Sector Z Inner Prey": {},

    "Sector 2 Start": {},
    "Sector 2 Storage Transport": {},
    "Sector 2 Storage Transport Top": {},
    "Sector 2 Supplies A": {},
    "Sector 2 Doctors' Offices": {},
    "Sector 2 Supercharge": {},
    "Sector 2 Medical Access Top": {},
    "Sector 2 Security Station": {},
    "Sector 2 Medical Bay": {},
    "Sector 2 Head Doctors' Office": {},
    "Sector 2 Break Room": {},
    "Sector 2 Storeroom": {},
    "Sector 2 Poster": {},

    "Sector 3 Start": {},
    "Sector 3 Software Development Left": {},
    "Sector 3 Software Development Right": {},
    "Sector 3 Storeroom Right": {},
    "Sector 3 Storage A Top": {},
    "Sector 3 Storage Elevator": {},
    "Sector 3 Storage B Interim": {},
    "Sector 3 Storage B": {},
    "Sector 3 Restricted Area Interim": {},
    "Sector 3 Restricted Area": {},
    "Sector 3 Reception": {},
    "Sector 3 Guards' Quarters": {},
    "Sector 3 Pulse Cannon": {},
    "Sector 3 Heavy Weapons Storage Interim": {},
    "Sector 3 Supercharge": {},
    "Sector 3 Outside Guard Tower": {},
    "Sector 3 Poster": {},
    "Sector 3 Maeja's Post": {},

    "Sector 4 Start": {},
    "Sector 4 Surveillance Control": {},
    "Sector 4 Main Storage Hub Right": {},
    "Sector 4 Storage Top Shredders": {},
    "Sector 4 Supercharge": {},
    "Sector 4 Main Storage": {},
    "Sector 4 Shaft to Terminals": {},
    "Sector 4 Guard Post": {},
    "Sector 4 Restricted Storage Access": {},
    "Sector 4 Reactor Core": {},
    "Sector 4 Classified Materials Access": {},
    "Sector 4 Final Terminal": {},
    "Sector 4 Final Shredders": {},
    "Sector 4 Poster": {},
    "Sector 4 Final Door": {},
    "Sector 4 End": {},

    "Sector 5 Start": {},
    "Sector 5 Main Region": {},
    "Sector 5 Storeroom 2": {},
    "Sector 5 Storage Control Sideroom": {},
    "Sector 5 Incoming Goods Sideroom": {},
    "Sector 5 Shocksplinter": {},
    "Sector 5 Storage Control Backup Bottom": {},
    "Sector 5 Storage Control Backup Middle": {},
    "Sector 5 Poster": {},
    "Sector 5 Ventilation": {},
    "Sector 5 Classified Materials Control": {},
    "Sector 5 Storeroom 3": {},
    "Sector 5 Classified Materials Storage": {},
    "Sector 5 Below Jump Upgrade": {},
    "Sector 5 Jump Upgrade": {},
    "Sector 5 Materials Analysis B Top": {},
    "Sector 5 Walkways Top Right": {},
    "Sector 5 Asha": {},

    "Sector 6 Start": {},
    "Sector 6 Shipping Control Shredder": {},
    "Sector 6 Ventilation Shaft": {},
    "Sector 6 Ventilation Sideroom 1": {},
    "Sector 6 Ventilation Sideroom 2": {},
    "Sector 6 Neoweapons Storage": {},
    "Sector 6 Security Network Admin": {},
    "Sector 6 Main Sector Elevator": {},
    "Sector 6 Neoweapons Research A Sideroom": {},
    "Sector 6 Elevator Shocksplinter": {},
    "Sector 6 Genetic Research Access": {},
    "Sector 6 Genetic Research": {},
    "Sector 6 CFIS": {},
    "Sector 6 Genetic Research Access Top": {},
    "Sector 6 Genetics Storage": {},
    "Sector 6 Poster": {},
    "Sector 6 Unused Storage Left": {},
    "Sector 6 Unused Storage Right": {},
    "Sector 6 Neoweapons Research MPFB": {},
    "Sector 6 Black Ops Left": {},
    "Sector 6 Black Ops Right": {},
    "Sector 6 Ribbon": {},
    "Sector 6 End Teleporter": {},
    "Sector 6 End Shaft": {},
    "Sector 6 End Logbook": {},
    "Sector 6 End Terminal": {},
    "Sector 6 End Shaft Top": {},
    "Sector 6 Control Room Access": {},

    "Sector 7 Start": {},
    "Sector 7 Real Start": {},
    "Sector 7 Exotic Technology Access": {},
    "Sector 7 Armory": {},
    "Sector 7 Armory Security Sideroom": {},
    "Sector 7 Heavy Weapons Armory Interim": {},
    "Sector 7 Heavy Weapons Armory": {},
    "Sector 7 Main Gate Access": {},
    "Sector 7 Internal Security": {},
    "Sector 7 Internal Security Top Left": {},
    "Sector 7 Internal Security Top Right": {},
    "Sector 7 Internal Security Weapons": {},
    "Sector 7 Data Processing": {},
    "Sector 7 Poster": {},
    "Sector 7 Phantom Hammer Control": {},
    "Sector 7 Assembly Hall": {},
    "Sector 7 Rooftops": {},
    "Sector 7 Crackers' Hideout": {},
    "Sector 7 Teleporter Logbooks": {},
    "Sector 7 Ribbon": {},

    "Sector 8 Start": {},
    "Sector 8 XQX Labs": {},
    "Sector 8 XQX Labs Tasen Sideroom": {},
    "Sector 8 Staff Storage": {},
    "Sector 8 Staff Storage Return Trip": {},
    "Sector 8 Poster": {},
    "Sector 8 Recreation": {},
    "Sector 8 Recreation Sideroom": {},

    "Sector 9 Start": {},
    "Sector 9 Guard Post Left": {},
    "Sector 9 Guard Post": {},
    "Sector 9 Materials Analysis": {},
    "Sector 9 Quarantine": {},
    "Sector 9 Special Security Unit": {},
    "Sector 9 Bulkhead Lock A Terminal": {},
    "Sector 9 Bulkhead Lock B Terminal": {},
    "Sector 9 Bulkhead Lock C Terminal": {},
    "Sector 9 Bulkhead Lock D Terminal": {},
    "Sector 9 Head Guards' Office": {},
    "Sector 9 Illegal Goods Storage": {},
    "Sector 9 Illegal Goods Storage Logbook": {},
    "Sector 9 Illegal Goods Storage Balcony": {},
    "Sector 9 Poster": {},
    "Sector 9 Banana Room": {},
    "Sector 9 Master Security Surveillance": {},
    "Sector 9 Security Gateway": {},
    "Sector 9 Break Room B": {},
    "Sector 9 Guards' Quarters": {},
    "Sector 9 Megacore Research": {},
    "Sector 9 Megacore Research Top Left": {},
    "Sector 9 Megacore Research Top Right": {},
    "Sector 9 Sector X Gateway": {},
    "Sector 9 Bunker Interim": {},
    "Sector 9 Bunker": {},
    "Sector 9 Bunker Top Secret Logbook Interim": {},
    "Sector 9 Bunker Top Secret Logbook": {},
    "Sector 9 Deep Sector 1": {},
    "Sector 9 Deep Sector 2": {},
    "Sector 9 Deep Sector 3": {},
    "Sector 9 Deep Sector 4": {},
    "Sector 9 Deep Sector 5": {},
    "Sector 9 Deep Sector 6": {},
    "Sector 9 Deep Sector 7": {},
    "Sector 9 Deep Sector 8": {},
    "Sector 9 Deep Sector 9": {},
    "Sector 9 Supercharge": {},
    "Sector 9 Iosa": {},

    "Sector X Start": {},
    "Sector X Daedalus Access": {},
    "Sector X Daedalus Labs A Balcony": {},
    "Sector X Ventilation Shaft": {},
    "Sector X Ventilation Shaft Below Shredders": {},
    "Sector X Poster": {},
    "Sector X Daedalus Labs A Turret": {},
    "Sector X Rooftop Elevator Interim": {},
    "Sector X Rooftop Elevator": {},
    "Sector X Rooftops": {},
    "Sector X Reactor Core": {},
    "Sector X Icarus Labs": {},
    "Sector X Icarus Labs Left": {},
    "Sector X Icarus Labs Right": {},
    "Sector X Megacore Control": {},
    "Sector X Megacore Control MPFB": {},
    "Sector X Megacore Control Bottom": {},
    "Sector X Asha Interim": {},
    "Sector X Asha": {},
    "Sector X After Asha": {},
    "Sector X Rooftop Elevator Top": {},
    "Sector X Rooftop Elevator CFIS": {},
    "Sector X Military Research": {},
    "Sector X Military Research Top Left": {},
    "Sector X Military Research Top Right": {},
    "Sector X Military Research Middle Left": {},
    "Sector X Military Research Middle Right": {},
    "Sector X Military Research Bottom": {},
    "Sector X Military Research Armory": {},
    "Sector X Helios Labs 1": {},
    "Sector X Helios Labs 1 Left": {},
    "Sector X Helios Labs 1 Right": {},
    "Sector X Helios Labs 2": {},
    "Sector X Helios Labs 3": {},
    "Sector X Helios Labs 3 Left": {},
    "Sector X Helios Labs 3 Right": {},
    "Sector X Restricted Area": {},
    "Sector X Maximum Charge Terminal": {},
    "Sector X Final Elevator Interim": {},
    "Sector X Final Elevator": {},
    "Sector X General Tor": {},

    "Sector Y": {}
}